// ==UserScript==
// @name         DockHAND 中文汉化
// @namespace    dockhand-zh
// @version      1.1.10
// @description  将 DockHAND Docker 管理面板界面汉化为简体中文，附带「还原翻译」开关按钮，默认开启
// @description:zh-CN  将 DockHAND Docker 管理面板界面汉化为简体中文，附带「还原翻译」开关按钮，默认开启
// @author       CoolMe
// @license      MIT
// @match        http://172.16.7.117:3011/*
// @match        http://localhost:3000/*
// @match        http://127.0.0.1:3000/*
// @run-at       document-idle
// @noframes
// @grant        none
// ==/UserScript==

(function () {
  "use strict";

  // ============ 字典：英文原文 -> 中文 ============
  const dict = {
    // ---- 页面标题 ----
    "Dockhand - Docker Management": "Dockhand - Docker 管理",
    "Dashboard - Dockhand": "仪表盘 - Dockhand",
    "Login - Dockhand": "登录 - Dockhand",
    "Containers - Dockhand": "容器 - Dockhand",
    "Images - Dockhand": "镜像 - Dockhand",
    "Networks - Dockhand": "网络 - Dockhand",
    "Volumes - Dockhand": "卷 - Dockhand",
    "Logs - Dockhand": "日志 - Dockhand",
    "Terminal - Dockhand": "终端 - Dockhand",
    "Activity - Dockhand": "活动 - Dockhand",
    "Audit log - Dockhand": "审计日志 - Dockhand",
    "Schedules - Dockhand": "计划任务 - Dockhand",
    "Registry - Dockhand": "镜像仓库 - Dockhand",
    "Profile - Dockhand": "个人资料 - Dockhand",
    "Stacks - Dockhand": "栈 - Dockhand",
    "Settings - Dockhand": "设置 - Dockhand",
    "Dockhand Docker Management": "Dockhand Docker 管理",

    // ---- 导航 / 页面 ----
    "Dashboard": "仪表盘",
    "Containers": "容器",
    "Logs": "日志",
    "Shell": "终端",
    "Stacks": "栈",
    "Images": "镜像",
    "Volumes": "卷",
    "Networks": "网络",
    "Registry": "镜像仓库",
    "Registries": "镜像仓库",
    "Activity": "活动",
    "Schedules": "计划任务",
    "Audit log": "审计日志",
    "Settings": "设置",
    "Backups": "备份",
    "Profile": "个人资料",
    "Users": "用户",
    "Roles": "角色",
    "Security": "安全",
    "General": "常规",
    "Environment": "环境",
    "Environments": "环境",
    "Notifications": "通知",
    "Authentication": "身份验证",
    "License": "许可证",
    "About": "关于",
    "Appearance": "外观",
    "Snapshots": "快照",
    "Favorites": "收藏",
    "Navigation": "导航",
    "Compose stacks": "Compose 栈",
    "System jobs": "系统任务",
    "Config sets": "配置集",
    "Group settings": "分组设置",
    "Notification channels": "通知渠道",
    "Manage registries": "管理镜像仓库",
    "Manage your account settings": "管理你的账户设置",

    // ---- 登录 / 账户 ----
    "Welcome back": "欢迎回来",
    "Sign in": "登录",
    "Sign out": "退出登录",
    "Sign in to your Dockhand account": "登录你的 Dockhand 账户",
    "Username": "用户名",
    "Password": "密码",
    "Enter your username": "输入用户名",
    "Enter your password": "输入密码",
    "New password": "新密码",
    "Current password": "当前密码",
    "Confirm password": "确认密码",
    "Repeat new password": "再次输入新密码",
    "Two-factor authentication": "双因素认证",
    "Two-factor authentication required": "需要双因素认证",
    "Authentication code": "验证码",
    "Enter code": "输入验证码",
    "Enter the 6-digit code from your authenticator app, or use a backup code": "请输入认证器应用中的 6 位验证码，或使用备用码",
    "Verifying...": "验证中...",
    "Signing in...": "登录中...",
    "Verify": "验证",
    "Back to login": "返回登录",
    "Login failed": "登录失败",
    "An unexpected error occurred": "发生意外错误",
    "Failed to initiate SSO login": "无法发起 SSO 登录",
    "Local account": "本地账户",
    "LDAP directory": "LDAP 目录",
    "Single sign-on": "单点登录",
    "Continue with": "继续使用",
    "or continue with": "或继续使用",
    "Sign in with": "使用以下方式登录",
    "Admin": "管理员",
    "User": "用户",
    "View profile": "查看个人资料",
    "Enterprise": "企业版",
    "Enterprise feature": "企业版功能",
    "Change password": "修改密码",
    "License expired": "许可证已过期",
    "Activate license": "激活许可证",
    "Licensed to": "授权给",
    "Managed by your SSO provider": "由你的 SSO 提供商管理",

    // ---- 通用操作 ----
    "Cancel": "取消",
    "Close": "关闭",
    "Close menu": "关闭菜单",
    "Add": "添加",
    "Clear": "清除",
    "Clear filters": "清除筛选",
    "Clear all filters": "清除全部筛选",
    "Refresh": "刷新",
    "Remove": "移除",
    "Delete": "删除",
    "Edit": "编辑",
    "Create": "创建",
    "Save": "保存",
    "Apply": "应用",
    "OK": "确定",
    "Retry": "重试",
    "Pull": "拉取",
    "Deploy": "部署",
    "Start": "启动",
    "Stop": "停止",
    "Restart": "重启",
    "Pause": "暂停",
    "Unpause": "恢复",
    "Rename": "重命名",
    "Restore": "恢复",
    "Reset": "重置",
    "Download": "下载",
    "Upload file": "上传文件",
    "Fix": "修复",
    "Test": "测试",
    "Run": "运行",
    "Run now": "立即运行",
    "Run container": "运行容器",
    "Back": "返回",
    "Next": "下一步",
    "Previous": "上一步",
    "Done": "完成",
    "Select": "选择",
    "Select all": "全选",
    "Browse": "浏览",
    "Use": "使用",
    "Configure": "配置",
    "Continue editing": "继续编辑",
    "Discard changes": "放弃更改",
    "Update anyway": "仍要更新",
    "Test connection": "测试连接",
    "Change permissions": "更改权限",
    "Browse files": "浏览文件",
    "View logs": "查看日志",
    "Open logs": "查看日志",
    "Open shell": "打开终端",
    "Open in new tab": "在新标签页打开",
    "Open terminal": "打开终端",
    "View details": "查看详情",
    "View changelog": "查看更新日志",
    "Add environment": "添加环境",
    "Edit environment": "编辑环境",
    "Edit environment settings": "编辑环境设置",
    "Delete environment": "删除环境",
    "Add label": "添加标签",
    "Add option": "添加选项",
    "Add mapping": "添加映射",
    "Clear logs": "清空日志",
    "Copy logs": "复制日志",
    "Download logs": "下载日志",
    "Refresh logs": "刷新日志",
    "Copy command": "复制命令",
    "Copy output": "复制输出",
    "Copy error": "复制错误",
    "Copy requires HTTPS": "复制功能需要 HTTPS",
    "Toggle Sidebar": "切换侧边栏",
    "Collapse sidebar": "折叠侧边栏",
    "Expand sidebar": "展开侧边栏",
    "Collapse all": "全部折叠",
    "Expand all": "全部展开",
    "Collapse": "折叠",
    "Expand": "展开",
    "Toggle theme": "切换主题",
    "Toggle auto-scroll": "切换自动滚动",
    "Toggle word wrap": "切换自动换行",
    "Toggle log theme": "切换日志主题",
    "Clear terminal (Ctrl+L)": "清空终端 (Ctrl+L)",
    "Auto-scroll": "自动滚动",
    "Wrap": "换行",
    "Change layout": "更改布局",
    "Customize menu": "自定义菜单",
    "Go to Settings": "前往设置",
    "Scan for vulnerabilities": "扫描漏洞",
    "Scan images for known security vulnerabilities": "扫描镜像的已知安全漏洞",
    "Enable scanning": "启用扫描",
    "Retry scan": "重试扫描",
    "Retry push": "重试推送",
    "Keep image": "保留镜像",
    "Tag image": "标记镜像",
    "Push to registry": "推送到镜像仓库",
    "Clone volume": "克隆卷",
    "Rename container": "重命名容器",
    "Remove from favorites": "取消收藏",
    "Remove schedule": "移除计划任务",
    "Remove user": "移除用户",
    "Copy as new role": "复制为新角色",
    "Delete snapshot": "删除快照",
    "Select registry": "选择镜像仓库",
    "Select for merge": "选择以合并",
    "Rotate repository password": "轮换仓库密码",
    "Dismiss all update indicators": "忽略所有更新提示",
    "Reconnect": "重新连接",
    "Parse": "解析",
    "Export": "导出",
    "Choose vulnerability scanner": "选择漏洞扫描器",
    "Force": "强制",
    "Adopt": "接管",
    "Adopt to:": "接管到：",
    "What happens when you adopt:": "接管后会发生什么：",
    "After restore": "恢复后",
    "Will be pushed as:": "将推送为：",
    "Run on your host:": "在你的主机上运行：",
    "Paste a full Docker URL to auto-fill the fields below": "粘贴完整 Docker URL 以自动填充下方字段",

    // ---- 状态 ----
    "Running": "运行中",
    "running": "运行中",
    "Paused": "已暂停",
    "paused": "已暂停",
    "Restarting": "重启中",
    "restarting": "重启中",
    "Exited": "已退出",
    "exited": "已退出",
    "Created": "创建时间",
    "created": "已创建",
    "Connected": "已连接",
    "Disconnected": "已断开",
    "Connecting...": "连接中...",
    "Connecting to environment...": "正在连接环境...",
    "Offline": "离线",
    "offline": "离线",
    "Enabled": "已启用",
    "Disabled": "已禁用",
    "Failed": "失败",
    "failed": "失败",
    "Success": "成功",
    "Error": "错误",
    "error": "错误",
    "Warning": "警告",
    "Loading...": "加载中...",
    "Loading more...": "加载更多...",
    "Initializing...": "初始化中...",
    "Initialized": "已初始化",
    "Checked": "已检查",
    "In use": "使用中",
    "Unused": "未使用",
    "Some unused": "部分未使用",
    "Not installed": "未安装",
    "Not tested": "未测试",
    "Needs init": "需要初始化",
    "Pending updates": "待更新",
    "Update available": "有可用更新",
    "Update available - click to update": "有可用更新 - 点击更新",
    "Update check failed": "检查更新失败",
    "Updating...": "更新中...",
    "Testing...": "测试中...",
    "Live": "实时",
    "All": "全部",
    "None": "无",
    "None (public)": "无（公开）",
    "None (public repository)": "无（公开仓库）",
    "None — disabled": "无 — 已禁用",
    "Never": "从不",
    "Never block": "从不屏蔽",
    "Always": "总是",
    "Custom": "自定义",
    "Unknown": "未知",
    "On failure": "失败时",
    "Unless stopped": "除非手动停止",
    "configured": "已配置",
    "Live updates connected": "实时更新已连接",
    "Live updates disconnected": "实时更新已断开",
    "Live updates active - grid will auto-refresh": "实时更新已启用 - 列表将自动刷新",
    "Connecting to live updates...": "正在连接实时更新...",
    "Connected - Live streaming": "已连接 - 实时流",
    "Streaming paused": "流式传输已暂停",
    "Retries": "重试次数",
    "On": "开启",
    "Off": "关闭",
    "Auto": "自动",
    "Blocked": "已屏蔽",
    "Progress": "进度",
    "Trigger": "触发器",
    "Selected:": "已选择：",
    "Preview:": "预览：",
    "Note:": "注意：",
    "Terminal:": "终端：",
    "Time:": "时间：",
    "(optional)": "（可选）",
    "(unavailable)": "（不可用）",
    "days": "天",
    "now": "刚刚",
    "Ready": "就绪",

    // ---- 字段 / 表头 ----
    "Name": "名称",
    "Name *": "名称 *",
    "Value": "值",
    "Key": "键",
    "Value (optional)": "值（可选）",
    "Labels": "标签",
    "Driver": "驱动",
    "Host": "主机",
    "Status": "状态",
    "Actions": "操作",
    "Action": "操作",
    "Modified": "修改时间",
    "Memory": "内存",
    "CPU": "CPU",
    "CPUs": "CPU",
    "Command": "命令",
    "Image": "镜像",
    "Container": "容器",
    "Volume": "卷",
    "Network": "网络",
    "Port": "端口",
    "Protocol": "协议",
    "Gateway": "网关",
    "Subnet": "子网",
    "Size": "大小",
    "Type": "类型",
    "Mode": "模式",
    "Scope": "作用域",
    "Version": "版本",
    "Platform": "平台",
    "Owner": "所有者",
    "Duration": "时长",
    "Total": "总计",
    "From": "来自",
    "To": "到",
    "Tag": "标签",
    "Repository": "仓库",
    "Repository URL": "仓库 URL",
    "Repository name": "仓库名称",
    "Branch": "分支",
    "Email": "邮箱",
    "Secret": "密钥",
    "Timestamp": "时间戳",
    "Timezone": "时区",
    "Metadata": "元数据",
    "Expires": "过期时间",
    "Description": "描述",
    "Internal": "内部",
    "Internal network": "内部网络",
    "External network": "外部网络",
    "External name (optional)": "外部名称（可选）",
    "Attachable": "可附加",
    "Read-only": "只读",
    "Privileged": "特权",
    "Processes": "进程",
    "Devices": "设备",
    "Device IDs": "设备 ID",
    "Capabilities": "功能权限",
    "DNS servers": "DNS 服务器",
    "Environment variables": "环境变量",
    "Environment variable": "环境变量",
    "Port mappings": "端口映射",
    "Volume mappings": "卷映射",
    "Host path": "主机路径",
    "Container path": "容器路径",
    "Container ID": "容器 ID",
    "Restart policy": "重启策略",
    "Network mode": "网络模式",
    "Driver options": "驱动选项",
    "Display name": "显示名称",
    "Image name": "镜像名称",
    "Image name/tag": "镜像名称/标签",
    "Stack name": "栈名称",
    "Environment ID": "环境 ID",
    "Target registry": "目标镜像仓库",
    "Source image": "源镜像",
    "File path": "文件路径",
    "Basic information": "基本信息",
    "Basic settings": "基本设置",
    "Additional options": "附加选项",
    "Security options": "安全选项",
    "IPAM configuration": "IPAM 配置",
    "Config": "配置",
    "Absolute (GB)": "绝对值 (GB)",
    "Percentage": "百分比",
    "Channel disabled globally": "通道已被全局禁用",
    "Production server": "生产服务器",
    "Dockhand host": "Dockhand 主机",
    "Server / IP *": "服务器 / IP *",
    "Quick URL (optional)": "快捷 URL（可选）",
    "New name": "新名称",
    "Additional mount options appended to the mount string": "追加到挂载字符串的额外挂载选项",
    "Ulimits": "资源限制",
    "Resources": "资源",
    "System": "系统",
    "Package": "软件包",

    // ---- 搜索 / 筛选 ----
    "Search...": "搜索...",
    "Search logs": "搜索日志",
    "Filter by name...": "按名称筛选...",
    "Filter networks...": "筛选网络...",
    "Search containers...": "搜索容器...",
    "Search images...": "搜索镜像...",
    "Search volumes...": "搜索卷...",
    "Search schedules...": "搜索计划任务...",
    "Search environments...": "搜索环境...",
    "Search running containers...": "搜索运行中的容器...",
    "Add user... (Enter)": "添加用户...（回车）",
    "Custom range...": "自定义范围...",
    "Search for pages and actions": "搜索页面和操作",
    "Command Palette": "命令面板",

    // ---- 连接方式 ----
    "Direct Docker connection": "直连 Docker",
    "Direct connection": "直连",
    "Unix socket connection": "Unix socket 连接",
    "Unix socket": "Unix socket",
    "Hawser agent (standard mode)": "Hawser 代理（标准模式）",
    "Hawser agent (edge mode)": "Hawser 代理（边缘模式）",
    "Hawser (standard)": "Hawser（标准）",
    "Hawser (edge)": "Hawser（边缘）",
    "Socket": "套接字",
    "Bridge": "网桥",
    "Bridge (default)": "网桥（默认）",
    "Passthru": "直通",
    "L2 (default)": "L2（默认）",
    "Shell (sh)": "Shell (sh)",

    // ---- 空态 / 提示 ----
    "No logs available": "暂无日志",
    "No metrics available": "暂无可用指标",
    "No environments": "暂无环境",
    "No environments found": "未找到环境",
    "No environments configured": "未配置环境",
    "No matching environments": "没有匹配的环境",
    "No networks found.": "未找到网络。",
    "No driver options configured": "未配置驱动选项",
    "No labels configured": "未配置标签",
    "No notification channels configured": "未配置通知渠道",
    "No shell available": "无可用终端",
    "No results found.": "未找到结果。",
    "No target registries available. Add a private registry in Settings.": "没有可用的目标镜像仓库。请在设置中添加私有仓库。",
    "Loading environments...": "正在加载环境...",
    "Loading logs...": "正在加载日志...",
    "Loading metadata...": "正在加载元数据...",
    "Loading release notes...": "正在加载更新说明...",
    "Detecting available shells...": "正在检测可用终端...",
    "Container is not running": "容器未运行",
    "Failed to load containers": "加载容器失败",
    "Unable to browse files": "无法浏览文件",
    "Stack already exists": "栈已存在",
    "Update status unknown — often a Docker Hub rate limit. Try again later.": "更新状态未知 — 通常是 Docker Hub 速率限制，请稍后重试。",
    "Auto-updates not available": "自动更新不可用",
    "Unsaved changes": "未保存的更改",
    "You have unsaved changes. Are you sure you want to close without saving?": "有未保存的更改，确定要不保存直接关闭吗？",
    "Invalid port (1-65535)": "端口无效 (1-65535)",
    "Name is required": "名称为必填项",
    "Dockhand update available": "Dockhand 有可用更新",
    "All containers healthy": "所有容器健康",
    "All containers": "所有容器",
    "All environments": "全部环境",
    "All repositories": "所有仓库",
    "All statuses": "全部状态",
    "All time": "全部时间",
    "Recent events": "最近事件",
    "Top containers by CPU": "CPU 占用最高的容器",
    "CPU & Memory history": "CPU 与内存历史",
    "Metrics collection disabled": "指标采集已禁用",
    "Metrics collection enabled": "指标采集已启用",
    "Activity collection enabled": "活动记录已启用",
    "Vulnerability scanning enabled": "漏洞扫描已启用",
    "Disk usage": "磁盘使用率",
    "Number of log lines to load": "要加载的日志行数",
    "Critical only": "仅严重",
    "Critical or high": "严重或高危",
    "Any vulnerabilities": "任意漏洞",
    "More than current image": "多于当前镜像",
    "Switch environment": "切换环境",
    "Select environment": "选择环境",
    "Environment offline": "环境离线",

    // ---- 主题 / 语言 ----
    "Light theme": "浅色主题",
    "Dark theme": "深色主题",
    "Theme: system": "主题：系统",
    "Theme: dark": "主题：深色",
    "Theme: light": "主题：浅色",
    "Language": "语言",
    "Font": "字体",
    "Daily": "每天",
    "Weekly": "每周",
    "Hourly": "每小时",
    "Monthly": "每月",
    "Stream": "流式",
    "Poll": "轮询",
    "Grid": "网格",
    "Tree": "树状",
    "Circle": "圆形",
    "Radial": "径向",

    // ---- 常用 toast 消息 ----
    "Failed to save": "保存失败",
    "Failed to save settings": "保存设置失败",
    "Failed to delete": "删除失败",
    "Failed to update schedule": "更新计划任务失败",
    "Failed to load snapshots": "加载快照失败",
    "Failed to load env variables": "加载环境变量失败",
    "Failed to fetch git credentials": "获取 Git 凭据失败",
    "Failed to prune volumes": "清理卷失败",
    "Failed to prune networks": "清理网络失败",
    "Connection test failed": "连接测试失败",
    "Init failed": "初始化失败",
    "Failed to toggle notification channel": "切换通知渠道失败",
    "Failed to toggle OIDC provider": "切换 OIDC 提供商失败",
    "Failed to toggle LDAP configuration": "切换 LDAP 配置失败",
    "Failed to set default registry": "设置默认镜像仓库失败",
    "Failed to save navigation preference": "保存导航偏好失败",
    "Failed to delete snapshot": "删除快照失败",
    "Failed to delete role": "删除角色失败",
    "Failed to delete repository": "删除仓库失败",
    "Failed to delete credential": "删除凭据失败",
    "Failed to delete OIDC provider": "删除 OIDC 提供商失败",
    "Failed to delete LDAP configuration": "删除 LDAP 配置失败",
    "Failed to clear update indicators": "清除更新提示失败",
    "Settings saved": "设置已保存",
    "Schedule saved": "计划任务已保存",
    "Schedule retention updated": "计划任务保留策略已更新",
    "Schedule is invalid": "计划任务无效",
    "User created": "用户已创建",
    "User updated": "用户已更新",
    "User deleted": "用户已删除",
    "Snapshot deleted": "快照已删除",
    "Repository deleted": "仓库已删除",
    "Registry deleted": "镜像仓库已删除",
    "Role deleted": "角色已删除",
    "Renamed successfully": "重命名成功",
    "Repository connection successful": "仓库连接成功",
    "OIDC connection successful": "OIDC 连接成功",
    "Test notification sent successfully": "测试通知发送成功",
    "Token generated successfully": "令牌生成成功",
    "Stack deployed from library template": "已从模板库部署栈",
    "Template reverted to default": "模板已恢复默认",
    "Permissions changed": "权限已更改",
    "Unused volumes pruned": "已清理未使用的卷",
    "Unused networks pruned": "已清理未使用的网络",
    "Trivy image updated": "Trivy 镜像已更新",
    "Trivy default arguments updated": "Trivy 默认参数已更新",
    "Scanner cleanup cron updated": "扫描器清理定时任务已更新",
    "Source added": "已添加源",
    "Source removed": "已移除源",
    "Scanner cache was already empty": "扫描器缓存已是空的",
    "Select a repository": "请选择仓库",
    "Select a backup repository": "请选择备份仓库",
    "Please select a repository first": "请先选择仓库",
    "Please enter a repository URL first": "请先输入仓库 URL",

    // ---- 实测补充 v1.1.0（dashboard / containers / images / stacks / volumes / networks / schedules / settings）----
    "Events": "事件",
    "Unlock tiles": "解锁磁贴",
    "Layout options": "布局选项",
    "Templates": "模板",
    "Sources": "模板源",
    "Check for updates": "检查更新",
    "Check for available updates": "检查可用更新",
    "Prune": "清理",
    "Prune unused": "清理未使用",
    "Prune containers": "清理容器",
    "Prune dangling images": "清理悬空镜像",
    "Prune unused images": "清理未使用镜像",
    "Prune volumes": "清理卷",
    "Prune networks": "清理网络",
    "Remove untagged intermediate layers (dangling images)": "删除未标记的中间层（悬空镜像）",
    "Remove ALL images not used by any container (including tagged images)": "删除所有未被任何容器使用的镜像（含已标记镜像）",
    "Switch to vertical layout (logs on side)": "切换为垂直布局（日志在侧边）",
    "Down (remove containers)": "停止（移除容器）",
    "Export volume as tar": "导出卷为 tar",
    "Connect container": "连接容器",
    "Copy network ID": "复制网络 ID",
    "Duplicate network": "复制网络",

    // ---- v1.1.3 用户反馈补充（logs / terminal / stacks / templates / registry / activity）----
    "Single": "单行",
    "Multi": "多行",
    "Grouped": "已分组",
    "Select a container from the list": "从列表中选择容器",
    "Shell:": "终端：",
    "User:": "用户：",
    "Select a container to open shell": "选择容器以打开终端",
    "Mem": "内存",
    "Net": "网络",
    "Disk": "磁盘",
    "Add to favorites": "添加到收藏",
    "Open logs inline": "内嵌打开日志",
    "Open logs in full view": "全屏打开日志",
    "Inspect container": "检查容器",
    "Filter containers...": "筛选容器...",
    "Search stacks...": "搜索栈...",
    "Notifications alt+T": "通知 alt+T",
    "Validate": "验证",
    "Add source": "添加源",
    "Columns": "列",
    "Exit": "退出",
    "Compose file location unknown. Click the stack name or edit button to locate it.": "Compose 文件位置未知。点击栈名称或编辑按钮以定位。",
    "Configure template catalog sources. Templates are fetched and cached for 1 hour.": "配置模板目录源。模板会被获取并缓存 1 小时。",
    // ---- v1.1.3 用户反馈 + 弹窗/子页补充 ----
    "Create compose stack": "创建 compose 栈",
    "Create a new Docker Compose stack": "创建新的 Docker Compose 栈",
    "Editor": "编辑器",
    "Graph": "图形",
    "Compose file": "Compose 文件",
    "Enter stack name above": "请在上方输入栈名称",
    "Env file": "环境变量文件",
    "Load": "加载",
    "required": "必填",
    "optional": "可选",
    "required w/ error": "必填且有错误",
    "No environment variables defined.": "未定义环境变量。",
    "Add your first variable": "添加第一个变量",
    "Create & Start": "创建并启动",
    "Browse for compose file": "浏览 compose 文件",
    "Copy path": "复制路径",
    "Browse for env file": "浏览环境变量文件",
    "Required variable (defined)": "必填变量（已定义）",
    "Form view": "表单视图",
    "Text view (raw .env file)": "文本视图（原始 .env 文件）",
    "Clear all variables?": "清除全部变量？",
    "Add registry": "添加镜像仓库",
    "Test connectivity": "测试连接",
    "Search": "搜索",
    "Search a registry to find and pull images": "搜索镜像仓库以查找并拉取镜像",
    "Test all": "全部测试",
    "Connection": "连接",
    "Features": "功能",
    "System prune": "清理系统",
    "Prune system": "清理系统",
    "Version": "版本",
    "Checking for updates...": "正在检查更新...",
    "System information": "系统信息",
    "Release notes": "更新说明",
    "Dependencies": "依赖",
    "Loading releases...": "正在加载更新说明...",
    "Loading dependencies...": "正在加载依赖...",

    // ---- v1.1.4 用户反馈精修（操作下拉/状态标签/时间范围/弹窗/设置子页）----
    "Partial": "部分运行",
    "Stopped": "已停止",
    "Not deployed": "未部署",
    "Update all containers with available updates": "批量更新所有有可用更新的容器",
    "Switch to horizontal layout (logs/terminal below)": "切换为水平布局（日志/终端在下方）",
    "Switch to horizontal layout (logs below)": "切换为水平布局（日志在下方）",
    "Select a container to view logs": "请选择容器以查看日志",
    "Select containers from the list to view merged logs": "请从列表中选择容器以查看合并日志",
    "Die": "异常退出",
    "Kill": "强制终止",
    "Destroy": "销毁",
    "Update": "更新",
    "Out of memory": "内存不足",
    "Health status": "健康状态",
    "Today": "今天",
    "Yesterday": "昨天",
    "Last 7 days": "最近 7 天",
    "Last 30 days": "最近 30 天",
    "This month": "本月",
    "Last month": "上月",
    "Add secret provider": "添加密钥提供方",
    "No secret providers": "暂无密钥提供方",
    "Add a provider (1Password, Infisical, HashiCorp Vault, ...) to load secrets at deploy time": "添加提供方（1Password、Infisical、HashiCorp Vault 等），用于在部署时加载密钥",

    // ---- v1.1.5 用户反馈精修（设置子页 / 栈图编辑器 / registry / activity）----
    "Show \"What's New\"": "显示\"新功能\"",
    "Show the \"What's New\" popup after upgrading to a new version": "升级到新版本后显示\"新功能\"弹窗",
    "Maximum number of log lines kept per container panel. Older lines are dropped when the limit is exceeded.": "每个容器面板保留的最大日志行数。超出限制时丢弃较早的行。",
    "Format when downloading files from containers or volumes. \"No archive\" emits raw bytes for single files; directories still download as tar.": "从容器或卷下载文件时的格式。\"无归档\"对单文件输出原始字节；目录仍以 tar 下载。",
    "Remove cached vulnerability databases to free disk space. Next scan will re-download fresh data (~200MB).": "删除缓存的漏洞数据库以释放磁盘空间。下次扫描将重新下载全新数据（约 200MB）。",
    "Automatically removes temporary containers used for browsing volume contents. Runs every 30 minutes and on startup.": "自动删除用于浏览卷内容的临时容器。每 30 分钟及启动时运行。",
    "Skip grype and trivy images during \"Prune all unused\"": "在\"清理全部未使用\"时跳过 grype 和 trivy 镜像",
    "What are config sets?": "什么是配置集？",
    "Add config set": "添加配置集",
    "Loading config sets...": "正在加载配置集...",
    "Configure notification channels to receive alerts about Docker events. Supports SMTP email and webhook URLs (Discord, Slack, Telegram, ntfy, Bark, Signal, Apprise, and more).": "配置通知渠道以接收 Docker 事件告警。支持 SMTP 邮件和 webhook URL（Discord、Slack、Telegram、ntfy、Bark、Signal、Apprise 等）。",
    "Detailed notification settings (event types, enable/disable) are configured per environment in Environment settings.": "详细的通知设置（事件类型、启用/禁用）在环境设置中按环境配置。",
    "Add channel": "添加渠道",
    "Add a channel to start receiving alerts about Docker events": "添加渠道以开始接收 Docker 事件告警",
    "Authentication is disabled - open access": "身份验证已禁用 - 开放访问",
    "Enable authentication to activate audit logging": "启用身份验证以激活审计日志",
    "Enable authentication to configure session settings": "启用身份验证以配置会话设置",
    "Search for images...": "搜索镜像...",
    "Clear all": "全部清除",
    "Container...": "容器...",
    "These variables will be written to a .env file in the stack directory and passed to the compose command.": "这些变量将被写入栈目录中的 .env 文件，并传递给 compose 命令。",
    "Copy": "复制",
    "Mount": "挂载",
    "Dependency": "依赖",
    "Click source service": "点击源服务",
    "Click target service": "点击目标服务",
    "Service": "服务",
    "State": "状态",
    "Health": "健康",
    "healthy": "健康",
    "Uptime": "运行时长",
    "Restarts": "重启次数",
    "Net I/O": "网络 I/O",
    "Disk I/O": "磁盘 I/O",
    "Ports": "端口",
    "Auto-update": "自动更新",
    "Stack": "栈",
    "Switch to vertical layout (logs/terminal on side)": "切换为垂直布局（日志/终端在侧边）",
    "Column settings": "列设置",
    "Daemon hostname / IP": "守护进程主机名 / IP",
    "Vulnerabilities": "漏洞",
    "Load from tar": "从 tar 加载",
    "Tags": "标签",
    "Updated": "更新时间",
    "From Git": "从 Git 部署",
    "Source": "来源",
    "Location": "位置",
    "Untracked": "未跟踪",
    "Not set": "未设置",
    "Usage": "使用量",
    "Used by": "使用者",
    "View Graph": "查看拓扑图",
    "built-in": "内置",
    "All types": "全部类型",
    "All envs": "全部环境",
    "Hide system": "隐藏系统任务",
    "Schedule": "计划任务",
    "Last run": "上次运行",
    "Next run": "下次运行",
    "Container event cleanup": "容器事件清理",
    "Removes container events older than 30 days": "删除 30 天前的容器事件",
    "Scanner cache cleanup": "扫描器缓存清理",
    "Removes scanner vulnerability database cache to reclaim disk space": "清理扫描器漏洞数据库缓存以回收磁盘空间",
    "Schedule execution cleanup": "计划任务执行记录清理",
    "Removes execution logs older than 30 days": "删除 30 天前的执行日志",
    "Volume helper cleanup": "卷辅助容器清理",
    "Cleans up temporary volume browser containers": "清理临时的卷浏览容器",
    "Secrets": "密钥",
    "ON": "开",
    "OFF": "关",
    "Show stopped containers": "显示已停止的容器",
    "Display stopped and exited containers in lists": "在列表中显示已停止和已退出的容器",
    "Highlight available updates": "高亮可用更新",
    "Highlight container rows in amber when updates are available": "有可用更新时以琥珀色高亮容器行",
    "Show changelog links": "显示更新日志链接",
    "Show a release-notes icon next to images with updates available": "在有可用更新的镜像旁显示更新说明图标",
    "Compact port display": "紧凑端口显示",
    "Show first port with +N count instead of all ports": "仅显示第一个端口并附 +N 计数",
    "Show exposed ports": "显示暴露端口",
    "Display internal container ports in the container list grid": "在容器列表中显示容器内部端口",
    "Show git commit hash": "显示 Git 提交哈希",
    "Display the deployed commit hash on the Git source badge in the stacks list": "在栈列表的 Git 来源徽章上显示部署的提交哈希",
    "Honor Traefik/Pangolin/Caddy labels": "识别 Traefik/Pangolin/Caddy 标签",
    "Show URLs inferred from Traefik and Pangolin labels alongside dockhand.url": "在 dockhand.url 旁显示由 Traefik 和 Pangolin 标签推断的 URL",
    "Time format": "时间格式",
    "Display timestamps in 12-hour (AM/PM) or 24-hour format": "以 12 小时（AM/PM）或 24 小时格式显示时间戳",
    "Date format": "日期格式",
    "How dates are displayed throughout the app": "日期在整个应用中的显示方式",
    "Default": "默认",
    "System UI": "系统 UI",
    "Font size": "字号",
    "Normal": "标准",
    "Grid font size": "表格字号",
    "Grid buttons": "表格按钮",
    "Terminal font": "终端字体",
    "System Monospace": "系统等宽字体",
    "Editor font": "编辑器字体",
    "Colored grid buttons": "彩色表格按钮",
    "Use semantic colors instead of muted gray": "使用语义颜色替代暗灰色",
    "Animate icons": "图标动画",
    "Spinners during pulls, scans and updates.": "拉取、扫描和更新期间显示加载动画。",
    "Indentation guides": "缩进参考线",
    "Vertical guides showing nesting depth in the code editor.": "在代码编辑器中显示嵌套深度的垂直参考线。",
    "Open the app on": "应用打开于",
    "Where the app opens (on the last-used environment).": "应用打开时使用的环境（上次使用的环境）。",
    "Environment click": "环境点击行为",
    "Where a tile click goes.": "点击环境磁贴后的跳转位置。",
    "Scheduling": "计划设置",
    "Default timezone": "默认时区",
    "Default timezone for new environments. Used for scheduled tasks like auto-updates.": "新环境的默认时区。用于自动更新等计划任务。",
    "Confirmations": "确认设置",
    "Confirm destructive actions": "破坏性操作需确认",
    "Show confirmation dialogs before deleting resources": "删除资源前显示确认对话框",
    "Logs & files": "日志与文件",
    "Log buffer size": "日志缓冲区大小",
    "Download format": "下载格式",
    "Format log timestamps": "格式化日志时间戳",
    "Convert ISO timestamps in logs to your configured date/time format": "将日志中的 ISO 时间戳转换为配置的日期/时间格式",
    "Compose template": "Compose 模板",
    "Default YAML content when creating a new stack.": "新建栈时的默认 YAML 内容。",
    "Save template": "保存模板",
    "Revert to default": "恢复默认",
    "Vulnerability scanners": "漏洞扫描器",
    "Grype image": "Grype 镜像",
    "Trivy image": "Trivy 镜像",
    "Docker image for Grype scanner. Pin to a specific version for supply chain security.": "Grype 扫描器的 Docker 镜像。固定到特定版本以保障供应链安全。",
    "Docker image for Trivy scanner. Pin to a specific version for supply chain security.": "Trivy 扫描器的 Docker 镜像。固定到特定版本以保障供应链安全。",
    "Default Grype arguments": "默认 Grype 参数",
    "Default Trivy arguments": "默认 Trivy 参数",
    "Advanced settings": "高级设置",
    "Scanner cache": "扫描器缓存",
    "Clear cache": "清除缓存",
    "Activity event collection mode": "活动事件采集模式",
    "Metrics collection interval": "指标采集间隔",
    "Delete executions older than specified days": "删除超过指定天数的执行记录",
    "Delete events older than specified days": "删除超过指定天数的容器事件",
    "Always enabled": "始终启用",
    "Remove cached vulnerability databases to reclaim disk space": "删除缓存的漏洞数据库以回收磁盘空间",
    "Protect scanner images from prune": "保护扫描器镜像不被清理",
    "Label filter matching": "标签过滤匹配方式",
    "Docker logs use UTC timestamps by default. When enabled, timestamps like": "Docker 日志默认使用 UTC 时间戳。启用后，类似以下的时间戳",
    "are converted to local time using your date/time settings.": "将按你的日期/时间设置转换为本地时间。",
    "as placeholder for the image name": "作为镜像名的占位符",
    "Sunday": "周日",

    // ---- docker 事件动词（最近事件列表）----
    "start": "启动",
    "create": "创建",
    "die": "退出",
    "kill": "强制终止",
    "stop": "停止",
    "rename": "重命名",
    "destroy": "销毁",
      // --- 设置>许可证 ---
      "Enter the name exactly as provided with your license": "请输入与许可证上完全一致的名称",
      "Activate your license to validate commercial use.": "激活您的许可证以验证商业用途。",
      "licenses unlock premium features including RBAC, LDAP and audit logs.":"许可证可解锁高级功能，包括基于角色的访问控制（RBAC）、轻量级目录访问协议（LDAP）和审计日志。",
      "License management": "许可证管理",
      "License name":"许可证名称",
      "Your Company Name":"您的公司名称",
      "License key":"许可证密钥",
      "Paste your license key here...": "在此粘贴你的许可证密钥...",

    // ---- v1.1.8 about 页补充 ----
    "Could not query registry": "无法查询镜像仓库",
    "Update check unavailable — click to retry": "检查更新不可用 — 点击重试",
    "Runtime": "运行时",
    "Database": "数据库",
    "Schema": "模式",
    "Edition": "版本",
    "Community": "社区版",
    "Terms": "服务条款",
    "Privacy": "隐私政策",
    "Submit issue or idea": "提交问题或建议",
    "Buy me a coffee": "请我喝杯咖啡",
    "Dockhand Community Edition is free and always will be. No strings attached. Like it? Fuel the dev with caffeine.": "Dockhand 社区版永久免费。无任何附加条件。喜欢它？用咖啡支持开发者吧。",
      "Current hostname (for license validation)":"当前主机名（用于许可证验证）",
    // ---- v1.1.9 源码提取：error/校验提示 + success 消息 ----
    "Access forbidden - check token permissions": "访问被拒绝 - 检查令牌权限",
    "Agent not connected": "代理未连接",
    "All fields are required": "所有字段均为必填项",
    "At least one webhook URL is required": "至少需要一个 webhook URL",
    "Authentication failed. Check registry credentials.": "认证失败。请检查镜像仓库凭据。",
    "Cancelled": "已取消",
    "Check failed: ": "检查失败：",
    "Connection error": "连接错误",
    "Connection failed": "连接失败",
    "Connection failed - check host and port": "连接失败 - 检查主机和端口",
    "Connection failed - click refresh to retry": "连接失败 - 点击刷新重试",
    "Connection failed. Click to retry.": "连接失败。点击重试。",
    "Connection lost": "连接丢失",
    "Connection lost: ": "连接丢失：",
    "Connection timed out": "连接超时",
    "Connection timeout": "连接超时",
    "Connection timeout or Docker not accessible": "连接超时或 Docker 不可访问",
    "Could not find image to push": "找不到要推送的镜像",
    "Could not reach the server to check the target paths.": "无法访问服务器以检查目标路径。",
    "Docker not accessible": "Docker 不可访问",
    "Docker socket not accessible": "Docker socket 不可访问",
    "Failed to activate license": "激活许可证失败",
    "Failed to browse registry": "浏览镜像仓库失败",
    "Failed to change password": "修改密码失败",
    "Failed to check for updates": "检查更新失败",
    "Failed to create environment": "创建环境失败",
    "Failed to create token": "创建令牌失败",
    "Failed to create user": "创建用户失败",
    "Failed to fetch logs: ": "获取日志失败：",
    "Failed to fetch processes": "获取进程失败",
    "Failed to load container data: ": "加载容器数据失败：",
    "Failed to load metadata": "加载元数据失败",
    "Failed to load profile": "加载个人资料失败",
    "Failed to read the snapshot": "读取快照失败",
    "Failed to remove avatar": "删除头像失败",
    "Failed to save credential": "保存凭据失败",
    "Failed to save git stack": "保存 Git 栈失败",
    "Failed to save repository": "保存仓库失败",
    "Failed to search images": "搜索镜像失败",
    "Failed to setup MFA": "设置 MFA 失败",
    "Failed to start backup": "启动备份失败",
    "Failed to start streaming": "启动流式传输失败",
    "Failed to test notification": "测试通知失败",
    "Failed to update container: ": "更新容器失败：",
    "Failed to update environment": "更新环境失败",
    "Failed to update profile": "更新个人资料失败",
    "Failed to update user": "更新用户失败",
    "Failed to upload avatar": "上传头像失败",
    "Failed to verify MFA": "验证 MFA 失败",
    "Host not found": "找不到主机",
    "Host not found - check the hostname": "找不到主机 - 检查主机名",
    "Host, from email, and at least one recipient are required": "主机、发件邮箱和至少一个收件人为必填项",
    "Image not found": "找不到镜像",
    "Invalid token - check that the Hawser token matches": "无效令牌 - 检查 Hawser 令牌是否匹配",
    "Name and URL are required": "名称和 URL 为必填项",
    "Name and host are required": "名称和主机为必填项",
    "Name and license key are required": "名称和许可证密钥为必填项",
    "No response body": "无响应内容",
    "Password is required": "密码为必填项",
    "Password must be at least 8 characters": "密码至少 8 个字符",
    "Passwords do not match": "两次密码不一致",
    "Permission denied - check socket permissions": "权限被拒绝 - 检查 socket 权限",
    "Please enter a name for the new volume": "请输入新卷的名称",
    "Please enter the verification code": "请输入验证码",
    "Please select an image file": "请选择镜像文件",
    "Repository fields are incomplete": "仓库字段不完整",
    "Socket not found - check the socket path": "找不到 socket - 检查 socket 路径",
    "Stream ended": "流已结束",
    "TLS certificate error - provide CA certificate for self-signed certs": "TLS 证书错误 - 为自签名证书提供 CA 证书",
    "TLS/SSL error - check certificate configuration": "TLS/SSL 错误 - 检查证书配置",
    "Token name is required": "令牌名称为必填项",
    "URL is required to test": "测试需要 URL",
    "insufficient_scope": "权限不足",
    "invalid_token": "无效令牌",
    "Activity log cleared": "活动日志已清除",
    "All containers are up to date": "所有容器均为最新",
    "All sources are reachable": "所有源均可访问",
    "Applied — no restart needed": "已应用 — 无需重启",
    "Backup image updated": "备份镜像已更新",
    "Backup schedule removed": "备份计划已移除",
    "Compose template updated": "Compose 模板已更新",
    "Config set deleted": "配置集已删除",
    "Connection test successful": "连接测试成功",
    "Connection works": "连接正常",
    "Container created successfully": "容器创建成功",
    "Container paused": "容器已暂停",
    "Container removed": "容器已移除",
    "Container restarted": "容器已重启",
    "Container started": "容器已启动",
    "Container stopped": "容器已停止",
    "Container unpaused": "容器已恢复",
    "Copied to clipboard": "已复制到剪贴板",
    "Credential deleted": "凭据已删除",
    "Default registry updated": "默认镜像仓库已更新",
    "Destination deleted": "目标已删除",
    "Edge mode - connection will be tested when agent connects": "边缘模式 - 代理连接时将测试连接",
    "Event cleanup cron updated": "事件清理定时任务已更新",
    "Event retention updated": "事件保留策略已更新",
    "Execution deleted": "执行记录已删除",
    "File saved": "文件已保存",
    "Grype default arguments updated": "Grype 默认参数已更新",
    "Grype image updated": "Grype 镜像已更新",
    "LDAP configuration deleted": "LDAP 配置已删除",
    "License activated successfully": "许可证激活成功",
    "License deactivated": "许可证已停用",
    "Live updates reconnected": "实时更新已重连",
    "Log buffer size updated": "日志缓冲区大小已更新",
    "MFA disabled for user": "已禁用该用户的 MFA",
    "Network ID copied to clipboard": "网络 ID 已复制到剪贴板",
    "New image tag copied": "新镜像标签已复制",
    "No compose stacks found in this directory": "此目录中未找到 compose 栈",
    "No dangling images to prune": "没有可清理的悬空镜像",
    "No environment variables found": "未找到环境变量",
    "No unused images to prune": "没有可清理的未使用镜像",
    "Notification channel added": "通知渠道已添加",
    "Notification channel deleted": "通知渠道已删除",
    "OIDC provider deleted": "OIDC 提供商已删除",
    "Secret provider deleted": "密钥提供方已删除",

    // ---- v1.1.10 源码提取：后端校验/错误提示 ----
    "Invalid 1Password Connect token": "1Password Connect 令牌无效",
    "Invalid Apprise URL format - missing protocol": "Apprise URL 格式无效 - 缺少协议",
    "Invalid Apprise URL. Expected: apprise://host[:port]/key": "Apprise URL 无效。期望格式：apprise://host[:port]/key",
    "Invalid CPU limit (e.g. 0.5, 1.5, 2)": "CPU 限制无效（例如 0.5、1.5、2）",
    "Invalid CPU period": "CPU 周期无效",
    "Invalid CPU quota": "CPU 配额无效",
    "Invalid CPU shares": "CPU 份额无效",
    "Invalid Docker API path": "Docker API 路径无效",
    "Invalid Gotify URL format. Expected: gotify://hostname/token": "Gotify URL 格式无效。期望：gotify://hostname/token",
    "Invalid ID token": "ID 令牌无效",
    "Invalid ID": "ID 无效",
    "Invalid IP address": "IP 地址无效",
    "Invalid IPv4 address": "IPv4 地址无效",
    "Invalid IPv6 address": "IPv6 地址无效",
    "Invalid JSON body": "JSON 正文无效",
    "Invalid MAC address (e.g., 02:42:ac:11:00:02)": "MAC 地址无效（例如 02:42:ac:11:00:02）",
    "Invalid MFA code": "MFA 验证码无效",
    "Invalid Mattermost URL format. Expected: mmost://[botname@]hostname[:port][/path]/token": "Mattermost URL 格式无效。期望：mmost://[botname@]hostname[:port][/path]/token",
    "Invalid Pushover URL format. Expected: pushover://user_key/api_token": "Pushover URL 格式无效。期望：pushover://user_key/api_token",
    "Invalid Signal URL. Expected: signal://host[:port]/+source/+target1[/+target2/...]": "Signal URL 无效。期望：signal://host[:port]/+source/+target1[/+target2/...]",
    "Invalid URL format": "URL 格式无效",
    "Invalid Workflows URL format. Expected: workflows://hostname/workflow/signature": "Workflows URL 格式无效。期望：workflows://hostname/workflow/signature",
    "Invalid YAML": "YAML 无效",
    "Invalid action. Use \"rename\", \"delete\", \"add\", or \"set-color\"": "操作无效。请使用 \"rename\"、\"delete\"、\"add\" 或 \"set-color\"",
    "Invalid actionIconSize": "actionIconSize 无效",
    "Invalid animateIcons": "animateIcons 无效",
    "Invalid auth type": "认证类型无效",
    "Invalid branch/ref name": "分支/引用名无效",
    "Invalid chmod mode": "chmod 模式无效",
    "Invalid coloredActionButtons": "coloredActionButtons 无效",
    "Invalid configId": "configId 无效",
    "Invalid configuration ID": "配置 ID 无效",
    "Invalid credential ID": "凭据 ID 无效",
    "Invalid dark theme": "dark theme 无效",
    "Invalid destination ID": "目标 ID 无效",
    "Invalid destinationId": "destinationId 无效",
    "Invalid editor font": "编辑器字体无效",
    "Invalid editorIndentGuides": "editorIndentGuides 无效",
    "Invalid env path": "环境变量路径无效",
    "Invalid env": "环境变量无效",
    "Invalid envClickPage": "envClickPage 无效",
    "Invalid environment ID": "环境 ID 无效",
    "Invalid execution ID": "执行 ID 无效",
    "Invalid expiration date": "过期日期无效",
    "Invalid file path": "文件路径无效",
    "Invalid font size": "字号无效",
    "Invalid font": "字体无效",
    "Invalid grid font size": "表格字号无效",
    "Invalid hideSystemJobs (must be boolean)": "hideSystemJobs 无效（必须为布尔值）",
    "Invalid image format": "镜像格式无效",
    "Invalid landingPage": "landingPage 无效",
    "Invalid license format": "许可证格式无效",
    "Invalid license signature": "许可证签名无效",
    "Invalid light theme": "light theme 无效",
    "Invalid memory value (e.g. 512m, 1g)": "内存值无效（例如 512m、1g）",
    "Invalid memory value": "内存值无效",
    "Invalid nonce": "nonce 无效",
    "Invalid or expired state": "状态无效或已过期",
    "Invalid password": "密码无效",
    "Invalid path": "路径无效",
    "Invalid policies JSON": "策略 JSON 无效",
    "Invalid port number": "端口号无效",
    "Invalid registry ID": "镜像仓库 ID 无效",
    "Invalid repository ID": "仓库 ID 无效",
    "Invalid repository URL": "仓库 URL 无效",
    "Invalid request body": "请求正文无效",
    "Invalid request body: content string required": "请求正文无效：需要 content 字符串",
    "Invalid request body: variables array required": "请求正文无效：需要 variables 数组",
    "Invalid request": "请求无效",
    "Invalid restic flags": "restic 参数无效",
    "Invalid restore request": "恢复请求无效",
    "Invalid scanner type": "扫描器类型无效",
    "Invalid schedule ID": "计划任务 ID 无效",
    "Invalid schedule type": "计划任务类型无效",
    "Invalid secret provider ID": "密钥提供方 ID 无效",
    "Invalid snapshot ID": "快照 ID 无效",
    "Invalid snapshotId": "snapshotId 无效",
    "Invalid stack ID": "栈 ID 无效",
    "Invalid stack data: missing name or composePath": "栈数据无效：缺少 name 或 composePath",
    "Invalid string length": "字符串长度无效",
    "Invalid system schedule ID": "系统计划任务 ID 无效",
    "Invalid targetName": "targetName 无效",
    "Invalid terminal font": "终端字体无效",
    "Invalid timezone": "时区无效",
    "Invalid token ID": "令牌 ID 无效",
    "Invalid token": "令牌无效",
    "Invalid username or password": "用户名或密码无效",
    "Invalid variable: key is required and must be a string": "变量无效：key 为必填且必须是字符串",
    "Invalid verification code": "验证码无效",
    "Invalid webhook secret": "webhook 密钥无效",
    "Invalid webhook signature": "webhook 签名无效",
    "A config set with this name already exists": "已存在同名配置集",
    "A credential with this name already exists": "已存在同名凭据",
    "A destination with this name already exists": "已存在同名目标",
    "A git stack with this name already exists for this environment": "此环境已存在同名 Git 栈",
    "A group with this name already exists": "已存在同名组",
    "A registry with this name already exists": "已存在同名镜像仓库",
    "A repository with this name already exists": "已存在同名仓库",
    "A secret provider with this name already exists": "已存在同名密钥提供方",
    "A stack with this name already exists on this environment": "此环境已存在同名栈",
    "An environment with this name already exists": "已存在同名环境",
    "Config set name already exists": "配置集名称已存在",
    "Destination already exists": "目标已存在",
    "Path already exists": "路径已存在",
    "Repository name already exists": "仓库名称已存在",
    "Role name already exists": "角色名称已存在",
    "Username already exists": "用户名已存在",
    "A valid provider type is required": "需要有效的提供方类型",
    "A webhook secret is required when the webhook is enabled": "启用 webhook 时需要 webhook 密钥",
    "Avatar data is required": "头像数据为必填项",
    "Base DN is required": "Base DN 为必填项",
    "Client ID is required when a client secret is set": "设置客户端密钥时需要客户端 ID",
    "Client ID is required": "客户端 ID 为必填项",
    "Client secret is required when a client ID is set": "设置客户端 ID 时需要客户端密钥",
    "Client secret is required": "客户端密钥为必填项",
    "Compose file content is required": "Compose 文件内容为必填项",
    "Compose file content or path is required": "Compose 文件内容或路径为必填项",
    "Compose path is required": "Compose 路径为必填项",
    "Config is required": "配置为必填项",
    "Container ID is required": "容器 ID 为必填项",
    "Container name is required": "容器名称为必填项",
    "Content is required": "内容为必填项",
    "Current password is required": "当前密码为必填项",
    "Either repositoryId or url is required": "需要 repositoryId 或 url",
    "Environment ID is required": "环境 ID 为必填项",
    "Export path is required": "导出路径为必填项",
    "File path is required": "文件路径为必填项",
    "Group name is required": "组名称为必填项",
    "Host is required for this connection type": "此连接类型需要主机",
    "Host is required": "主机为必填项",
    "Image name is required": "镜像名称为必填项",
    "Issuer URL is required": "签发者 URL 为必填项",
    "MFA token is required": "MFA 令牌为必填项",
    "Mode is required (e.g., \"755\" or \"u+x\")": "模式为必填项（例如 \"755\" 或 \"u+x\"）",
    "Mode is required": "模式为必填项",
    "Network name is required": "网络名称为必填项",
    "New name is required": "新名称为必填项",
    "New path is required": "新路径为必填项",
    "New volume name is required": "新卷名称为必填项",
    "Old path is required": "旧路径为必填项",
    "Password is required for password authentication": "密码认证需要密码",
    "Password is required to create an API token": "创建 API 令牌需要密码",
    "Path is required": "路径为必填项",
    "Redirect URI is required": "重定向 URI 为必填项",
    "Registry ID is required": "镜像仓库 ID 为必填项",
    "Repository URL is required to test": "测试需要仓库 URL",
    "Repository URL is required": "仓库 URL 为必填项",
    "Repository URL or existing repository ID is required": "需要仓库 URL 或已有的仓库 ID",
    "Repository name is required": "仓库名称为必填项",
    "Request body (an image tar) is required": "需要请求正文（镜像 tar）",
    "Role ID is required": "角色 ID 为必填项",
    "Role name is required": "角色名称为必填项",
    "SSH private key is required for SSH authentication": "SSH 认证需要 SSH 私钥",
    "SSH private key is required": "SSH 私钥为必填项",
    "Search term is required": "搜索词为必填项",
    "Server URL is required": "服务器 URL 为必填项",
    "Server is required": "服务器为必填项",
    "Share path is required": "共享路径为必填项",
    "Stack name is required": "栈名称为必填项",
    "Tag is required": "标签为必填项",
    "Target path is required": "目标路径为必填项",
    "Template is required": "模板为必填项",
    "Token ID is required": "令牌 ID 为必填项",
    "Token name must be 255 characters or less": "令牌名称不能超过 255 个字符",
    "URL is required": "URL 为必填项",
    "User ID is required": "用户 ID 为必填项",
    "Username is required": "用户名为必填项",
    "Volume name is required": "卷名称为必填项",
    "Zabbix API token is required": "Zabbix API 令牌为必填项",
    "Zabbix host is required": "Zabbix 主机为必填项",
    "Zabbix item key is required": "Zabbix 监控项键为必填项",
    "Action must be \"add\", \"remove\", \"update\", or \"reorder\"": "操作必须为 \"add\"、\"remove\"、\"update\" 或 \"reorder\"",
    "Action must be \"add\", \"remove\", or \"reorder\"": "操作必须为 \"add\"、\"remove\" 或 \"reorder\"",
    "Bitwarden Project selector must be a valid UUID": "Bitwarden 项目选择器必须是有效的 UUID",
    "Bitwarden bws command exceeded the stderr limit": "Bitwarden bws 命令超出 stderr 限制",
    "Bitwarden bws command exceeded the stdout limit": "Bitwarden bws 命令超出 stdout 限制",
    "Bitwarden bws executable path must be absolute": "Bitwarden bws 可执行文件路径必须是绝对路径",
    "Bitwarden bws version must be >=2.1.0 and <3.0.0": "Bitwarden bws 版本必须 >=2.1.0 且 <3.0.0",
    "Cannot access path": "无法访问路径",
    "Cannot auto-update Dockhand itself": "无法自动更新 Dockhand 自身",
    "Cannot auto-update Hawser agent": "无法自动更新 Hawser 代理",
    "Cannot change the destination while a backup is running for this config": "此配置正在备份，无法更改目标",
    "Cannot delete critical system path": "无法删除关键系统路径",
    "Cannot delete environment with empty name": "无法删除名称为空的环境",
    "Cannot delete image: it has dependent child images. Delete those first or use force delete.": "无法删除镜像：它存在依赖的子镜像。请先删除子镜像或使用强制删除。",
    "Cannot delete image: it is being used by a running container. Stop the container first.": "无法删除镜像：它正被运行中的容器使用。请先停止该容器。",
    "Cannot delete system roles": "无法删除系统角色",
    "Cannot delete this environment": "无法删除此环境",
    "Cannot enable authentication without any users. Create a user first.": "没有任何用户时无法启用身份验证。请先创建用户。",
    "Cannot modify an admin account": "无法修改管理员账户",
    "Cannot modify system roles": "无法修改系统角色",
    "Cannot read a directory": "无法读取目录",
    "Cannot write masked placeholder \"***\" to .env file - this would corrupt secret values": "无法将掩码占位符 \"***\" 写入 .env 文件 - 这会破坏密钥值",
    "Compose file must be a YAML mapping at the top level": "Compose 文件顶层必须是 YAML 映射",
    "Compose file must be within the context directory": "Compose 文件必须位于上下文目录内",
    "Config must be an object": "配置必须是对象",
    "Containers array is required and must not be empty": "容器数组为必填且不能为空",
    "Content is too large (max 1MB)": "内容过大（最大 1MB）",
    "Context directory must be within the repository": "上下文目录必须位于仓库内",
    "Current password does not match": "当前密码不匹配",
    "Current password is incorrect": "当前密码不正确",
    "Directory is not empty": "目录不为空",
    "Directory not empty": "目录不为空",
    "Docker disk usage exceeds threshold": "Docker 磁盘使用量超过阈值",
    "Event poll interval must be between 30s and 300s": "事件轮询间隔必须在 30 秒到 300 秒之间",
    "Expiration date must be in the future": "过期日期必须在未来",
    "File is too large to edit (max 1MB)": "文件过大，无法编辑（最大 1MB）",
    "File is too large to view (max 1MB)": "文件过大，无法查看（最大 1MB）",
    "Image is in use and cannot be deleted": "镜像正在使用中，无法删除",
    "Image too large": "镜像过大",
    "Image too large. Maximum size is 500KB.": "镜像过大。最大为 500KB。",
    "Metrics collection interval must be between 10s and 300s": "指标采集间隔必须在 10 秒到 300 秒之间",
    "Name cannot be empty": "名称不能为空",
    "New label cannot be empty": "新标签不能为空",
    "New password must be at least 8 characters": "新密码至少 8 个字符",
    "Path must be absolute": "路径必须是绝对路径",
    "Proton Pass pass-cli command exceeded the stderr limit": "Proton Pass pass-cli 命令超出 stderr 限制",
    "Proton Pass pass-cli command exceeded the stdout limit": "Proton Pass pass-cli 命令超出 stdout 限制",
    "Proton Pass pass-cli executable path must be absolute": "Proton Pass pass-cli 可执行文件路径必须是绝对路径",
    "Proton Pass reference must be pass://SHARE_ID/ITEM_ID[/FIELD]": "Proton Pass 引用必须是 pass://SHARE_ID/ITEM_ID[/FIELD]",
    "Proton Pass vault selector is invalid": "Proton Pass 保险库选择器无效",
    "Range start must be less than end": "范围起点必须小于终点",
    "Registry cannot be deleted": "镜像仓库无法删除",
    "Repository URL must be a remote (https/ssh/git), not a local path": "仓库 URL 必须是远程地址（https/ssh/git），不能是本地路径",
    "Repository is not reachable or the password is incorrect": "仓库不可达或密码不正确",
    "System schedules cannot be paused": "系统计划任务无法暂停",
    "System schedules cannot be removed": "系统计划任务无法移除",
    "Two services cannot bind the same host port; change one.": "两个服务不能绑定同一主机端口，请更改其中一个。",
    "Type must be \"file\" or \"directory\"": "类型必须为 \"file\" 或 \"directory\"",
    "Type must be smtp or apprise": "类型必须为 smtp 或 apprise",
    "Webhook config requires at least one URL": "webhook 配置至少需要一个 URL",

  };

  // ============ 插值模板：正则 -> 替换 ============
  const patterns = [
    [/^License expires in (\d+) days$/, "许可证将在 $1 天后到期"],
    [/^(\d+) of (\d+)$/, "$1 / $2"],
    [/^Cannot switch to "(.+?)" - (.+)$/, '无法切换到 "$1" - $2'],
    [/^(\d+) cores?$/, "$1 核"],
    [/^(.+?) RAM$/, "$1 内存"],
    [/^(\d+) unhealthy$/, "$1 个不健康"],
    [/^(\d+) restarting$/, "$1 个重启中"],
    [/^(\d+) today$/, "今日 $1"],
    [/^(\d+)m$/, "$1 分钟"],
    [/^(\d+)h$/, "$1 小时"],
    [/^(\d+)d$/, "$1 天"],
    [/^(\d+) total$/, "共 $1"],
    [/^(\d+) days$/, "$1 天"],
    [/^Failed to (.+)$/, "失败：$1"],
    // ---- 实测补充 v1.1.0 ----
    [/^\/ (\d+) total$/, "/ 共 $1"],
    [/^(\d+) seconds?$/, "$1 秒"],
    [/^(\d+) minutes?$/, "$1 分钟"],
    [/^(\d+) hours?$/, "$1 小时"],
    [/^(\d+) weeks?$/, "$1 周"],
    [/^(\d+) months?$/, "$1 个月"],
    [/^(\d+) years?$/, "$1 年"],
    [/^In (\d+) hours?$/, "$1 小时后"],
    [/^In (\d+) min(ute)?s?$/, "$1 分钟后"],
    [/^(\d+)d (\d+)h$/, "$1 天 $2 小时"],
    [/^Every (\d+) minutes$/, "每 $1 分钟"],
    [/^At ([\d:]+ [AP]M)$/, "于 $1"],
    [/^At ([\d:]+ [AP]M), only on Sunday$/, "每周日 $1"],
    // ---- v1.1.3 新增 ----
    [/^Checking (\d+)\/(\d+)$/, "检查中 $1/$2"],
    [/^(\d+) update\(s\) available \((\d+) failed to check\)$/, "$1 个可用更新（$2 个检查失败）"],
    [/^(.+): Could not query registry$/, "$1：无法查询镜像仓库"],
    [/^(\d+) volumes? mounted$/, "挂载了 $1 个卷"],
    [/^Version (.+)$/, "版本 $1"],
    [/^Update all \((\d+)\)$/, "全部更新 ($1)"],
    [/^(\d+) of (\d+) selected$/, "已选 $1/$2"],
    [/^Uptime (.+)$/, "运行时长 $1"]
  ];

  // ============ 翻译引擎 ============
  const ATTRS = ["placeholder", "title", "aria-label"];
  const SKIP_TAGS = new Set(["SCRIPT", "STYLE", "CODE", "PRE", "TEXTAREA", "NOSCRIPT", "KBD", "SAMP"]);
  const MAX_LEN = 300;

  // 翻译记录（用于还原）
  const textLog = new Map(); // textNode -> 原始完整文本
  const attrLog = new Map(); // element -> { attr: 原始值 }

  let enabled = localStorage.getItem("dh_zh_on") !== "0"; // 默认开启翻译

  function lookup(s) {
    if (dict[s]) return dict[s];
    const folded = s.replace(/\s+/g, " "); // 空白折叠：多行/制表符文本节点兜底
    if (dict[folded]) return dict[folded];
    if (s.length <= MAX_LEN) {
      for (const [re, rep] of patterns) {
        if (re.test(s)) return s.replace(re, rep);
      }
    }
    return null;
  }

  function translateTextNode(node) {
    const raw = node.nodeValue;
    if (!raw) return;
    const m = raw.match(/^(\s*)([\s\S]*?)(\s*)$/);
    if (!m || !m[2] || m[2].length > MAX_LEN) return;
    const zh = lookup(m[2]);
    if (!zh || zh === m[2]) return;
    textLog.set(node, raw); // 命中时当前必为英文，记录原始值
    node.nodeValue = m[1] + zh + m[3];
  }

  function translateElement(el) {
    for (const a of ATTRS) {
      const v = el.getAttribute(a);
      if (!v || v.length > MAX_LEN) continue;
      const zh = lookup(v);
      if (!zh || zh === v) continue;
      let log = attrLog.get(el);
      if (!log) { log = {}; attrLog.set(el, log); }
      if (!(a in log)) log[a] = v;
      el.setAttribute(a, zh);
    }
  }

  function isInEditor(el) {
    // 跳过代码编辑器（CodeMirror 6 / Monaco / contenteditable）内的文本
    return !!(el && el.closest && el.closest(
      '.cm-editor, .cm-content, .cm-line, [contenteditable="true"], [contenteditable=""], textarea, pre, code'
    ));
  }

  function walk(root) {
    if (root.nodeType === Node.TEXT_NODE) { if (!isInEditor(root.parentNode)) translateTextNode(root); return; }
    if (root.nodeType !== Node.ELEMENT_NODE) return;
    if (root.id === "dh-zh-toggle") return; // 不处理自身按钮
    translateElement(root); // 先翻译属性（含 textarea/input 的 placeholder），SKIP 元素也要翻属性
    if (SKIP_TAGS.has(root.tagName)) return; // 但跳过内容子树（脚本/样式/代码/textarea 内容不翻）
    if (isInEditor(root)) return; // 不进入代码编辑器子树
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT, {
      acceptNode(n) {
        if (n.nodeType === Node.TEXT_NODE) {
          return isInEditor(n.parentNode) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
        }
        if (n.id === "dh-zh-toggle") return NodeFilter.FILTER_REJECT;
        translateElement(n); // 翻译该元素属性（textarea/input placeholder 等）
        if (SKIP_TAGS.has(n.tagName) || isInEditor(n)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    for (let n = walker.nextNode(); n; n = walker.nextNode()) {
      if (n.nodeType === Node.TEXT_NODE) translateTextNode(n);
      else translateElement(n);
    }
  }

  function restoreAll() {
    for (const [node, orig] of textLog) {
      if (node.isConnected) node.nodeValue = orig;
    }
    textLog.clear();
    for (const [el, log] of attrLog) {
      if (el.isConnected) for (const a in log) el.setAttribute(a, log[a]);
    }
    attrLog.clear();
  }

  // ============ MutationObserver ============
  const mo = new MutationObserver((muts) => {
    if (btn && !btn.isConnected && document.body) document.body.appendChild(btn); // 维持按钮存在
    if (!enabled) return;
    for (const mu of muts) {
      if (mu.type === "characterData") { translateTextNode(mu.target); continue; }
      if (mu.type === "attributes") { translateElement(mu.target); continue; } // 动态设置的 title/placeholder 等
      for (const n of mu.addedNodes) walk(n);
    }
  });

  function start() {
    mo.observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATTRS });
    walk(document.documentElement);
  }

  // ============ 开关按钮 ============
  let btn = null;

  function makeButton() {
    btn = document.createElement("button");
    btn.id = "dh-zh-toggle";
    btn.style.cssText = [
      "position:fixed", "right:16px", "bottom:16px", "z-index:2147483647",
      "padding:7px 16px", "border:none", "border-radius:999px",
      "background:rgba(28,30,34,0.88)", "color:#fff",
      "font:500 12px/1.4 system-ui,sans-serif", "letter-spacing:0.5px",
      "cursor:pointer", "box-shadow:0 2px 10px rgba(0,0,0,0.3)",
      "transition:background 0.15s", "user-select:none"
    ].join(";");
    btn.addEventListener("mouseenter", () => { btn.style.background = "rgba(50,54,60,0.92)"; });
    btn.addEventListener("mouseleave", () => { btn.style.background = "rgba(28,30,34,0.88)"; });
    btn.addEventListener("click", toggle);
    updateLabel();
    document.body.appendChild(btn);
  }

  function updateLabel() {
    if (!btn) return;
    btn.textContent = enabled ? "还原翻译" : "开启翻译";
    btn.title = enabled ? "点击还原为英文" : "点击开启中文翻译";
  }

  function toggle() {
    enabled = !enabled;
    localStorage.setItem("dh_zh_on", enabled ? "1" : "0");
    if (enabled) {
      walk(document.documentElement); // 重新翻译当前 DOM
    } else {
      restoreAll(); // 还原所有已翻译文本
    }
    updateLabel();
  }

  // ============ 启动 ============
  if (document.body) {
    makeButton();
    if (enabled) start();
    else mo.observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATTRS }); // 仍监听以维持按钮存在
  } else {
    document.addEventListener("DOMContentLoaded", () => {
      makeButton();
      start();
    });
  }
})();
