// ==UserScript==
// @name         DockHAND 中文汉化
// @namespace    dockhand-zh
// @version      1.1.15
// @description  将 DockHAND Docker 管理面板界面汉化为简体中文，附带「还原翻译」开关按钮，默认开启
// @description:zh-CN  将 DockHAND Docker 管理面板界面汉化为简体中文，附带「还原翻译」开关按钮，默认开启
// @author       CoolMe
// @license      MIT
// @match        http://172.16.7.117:3011/*
// @match        http://localhost:3000/*
// @match        http://127.0.0.1:3000/*
// @run-at       document-idle
// @noframes
// @grant        none
// ==/UserScript==

(function () {
  "use strict";

  // ============ 字典：英文原文 -> 中文 ============
  const dict = {
    // ===================== 通用 (448) =====================
    "Dockhand - Docker Management": "Dockhand - Docker 管理",
    "Dashboard - Dockhand": "仪表盘 - Dockhand",
    "Settings - Dockhand": "设置 - Dockhand",
    "Audit log": "审计日志",
    "Compose stacks": "Compose 栈",
    "System jobs": "系统任务",
    "Config sets": "配置集",
    "Notification channels": "通知渠道",
    "New password": "新密码",
    "Current password": "当前密码",
    "Two-factor authentication": "双因素认证",
    "Enterprise feature": "企业版功能",
    "Activate license": "激活许可证",
    "Licensed to": "授权给",
    "Close menu": "关闭菜单",
    "Clear filters": "清除筛选",
    "Clear all filters": "清除全部筛选",
    "Upload file": "上传文件",
    "Run now": "立即运行",
    "Select all": "全选",
    "Continue editing": "继续编辑",
    "Discard changes": "放弃更改",
    "Update anyway": "仍要更新",
    "Test connection": "测试连接",
    "Browse files": "浏览文件",
    "View logs": "查看日志",
    "Open terminal": "打开终端",
    "View details": "查看详情",
    "View changelog": "查看更新日志",
    "Add environment": "添加环境",
    "Edit environment": "编辑环境",
    "Add label": "添加标签",
    "Copy requires HTTPS": "复制功能需要 HTTPS",
    "Change layout": "更改布局",
    "Go to Settings": "前往设置",
    "Retry scan": "重试扫描",
    "Retry push": "重试推送",
    "Remove schedule": "移除计划任务",
    "Remove user": "移除用户",
    "Delete snapshot": "删除快照",
    "Select registry": "选择镜像仓库",
    "Dismiss all update indicators": "忽略所有更新提示",
    "Will be pushed as:": "将推送为：",
    "Connecting...": "连接中...",
    "Loading...": "加载中...",
    "Loading more...": "加载更多...",
    "Initializing...": "初始化中...",
    "Not tested": "未测试",
    "Update available - click to update": "有可用更新 - 点击更新",
    "Update check failed": "检查更新失败",
    "Updating...": "更新中...",
    "Testing...": "测试中...",
    "On failure": "失败时",
    "Unless stopped": "除非手动停止",
    "Note:": "注意：",
    "(optional)": "（可选）",
    "(unavailable)": "（不可用）",
    "Name *": "名称 *",
    "Repository URL": "仓库 URL",
    "Repository name": "仓库名称",
    "Internal network": "内部网络",
    "External network": "外部网络",
    "DNS servers": "DNS 服务器",
    "Environment variables": "环境变量",
    "Port mappings": "端口映射",
    "Volume mappings": "卷映射",
    "Host path": "主机路径",
    "Container path": "容器路径",
    "Container ID": "容器 ID",
    "Restart policy": "重启策略",
    "Network mode": "网络模式",
    "Driver options": "驱动选项",
    "Display name": "显示名称",
    "Image name/tag": "镜像名称/标签",
    "Environment ID": "环境 ID",
    "Target registry": "目标镜像仓库",
    "Source image": "源镜像",
    "Basic information": "基本信息",
    "Basic settings": "基本设置",
    "IPAM configuration": "IPAM 配置",
    "New name": "新名称",
    "Search...": "搜索...",
    "Filter by name...": "按名称筛选...",
    "Search environments...": "搜索环境...",
    "Add user... (Enter)": "添加用户...（回车）",
    "Custom range...": "自定义范围...",
    "Direct Docker connection": "直连 Docker",
    "Unix socket connection": "Unix socket 连接",
    "Hawser agent (standard mode)": "Hawser 代理（标准模式）",
    "Hawser agent (edge mode)": "Hawser 代理（边缘模式）",
    "No logs available": "暂无日志",
    "No environments found": "未找到环境",
    "No environments configured": "未配置环境",
    "No matching environments": "没有匹配的环境",
    "No labels configured": "未配置标签",
    "No notification channels configured": "未配置通知渠道",
    "No target registries available. Add a private registry in Settings.": "没有可用的目标镜像仓库。请在设置中添加私有仓库。",
    "Loading environments...": "正在加载环境...",
    "Loading metadata...": "正在加载元数据...",
    "Loading release notes...": "正在加载更新说明...",
    "Detecting available shells...": "正在检测可用终端...",
    "Failed to load containers": "加载容器失败",
    "Unable to browse files": "无法浏览文件",
    "Update status unknown — often a Docker Hub rate limit. Try again later.": "更新状态未知 — 通常是 Docker Hub 速率限制，请稍后重试。",
    "Unsaved changes": "未保存的更改",
    "You have unsaved changes. Are you sure you want to close without saving?": "有未保存的更改，确定要不保存直接关闭吗？",
    "All containers": "所有容器",
    "All environments": "全部环境",
    "All repositories": "所有仓库",
    "All statuses": "全部状态",
    "All time": "全部时间",
    "Metrics collection enabled": "指标采集已启用",
    "Activity collection enabled": "活动记录已启用",
    "Vulnerability scanning enabled": "漏洞扫描已启用",
    "Layout options": "布局选项",
    "Compose file": "Compose 文件",
    "Access forbidden - check token permissions": "访问被拒绝 - 检查令牌权限",
    "Agent not connected": "代理未连接",
    "Authentication failed. Check registry credentials.": "认证失败。请检查镜像仓库凭据。",
    "Connection error": "连接错误",
    "Connection failed": "连接失败",
    "Connection failed - check host and port": "连接失败 - 检查主机和端口",
    "Connection lost": "连接丢失",
    "Connection timeout": "连接超时",
    "Connection timeout or Docker not accessible": "连接超时或 Docker 不可访问",
    "Docker socket not accessible": "Docker socket 不可访问",
    "Host not found": "找不到主机",
    "Host not found - check the hostname": "找不到主机 - 检查主机名",
    "Image not found": "找不到镜像",
    "Invalid token - check that the Hawser token matches": "无效令牌 - 检查 Hawser 令牌是否匹配",
    "Permission denied - check socket permissions": "权限被拒绝 - 检查 socket 权限",
    "Socket not found - check the socket path": "找不到 socket - 检查 socket 路径",
    "TLS certificate error - provide CA certificate for self-signed certs": "TLS 证书错误 - 为自签名证书提供 CA 证书",
    "TLS/SSL error - check certificate configuration": "TLS/SSL 错误 - 检查证书配置",
    "environment:": "环境：",
    "CA certificate": "CA 证书",
    "Client certificate": "客户端证书",
    "Client key": "客户端密钥",
    "HTTPS (TLS)": "HTTPS (TLS)",
    "Alert configuration coming soon": "告警配置即将推出",
    "No alerts configured": "未配置告警",
    "Containers built from scratch or distroless images often don't include shells.": "从头构建或 distroless 镜像的容器通常不含 shell。",
    "Auto-update": "自动更新",
    "Copied!": "已复制！",
    "Custom...": "自定义...",
    "Image:": "镜像：",
    "Restoring…": "正在恢复…",
    "read-only": "只读",
    "Auto-scroll": "自动滚动",
    "Time:": "时间：",
    "Terminal:": "终端：",
    "Shell:": "终端：",
    "User:": "用户：",
    "Selected:": "已选择：",
    "Current:": "当前：",
    "New:": "新建：",
    "Re-check": "重新检查",
    "Stack:": "栈：",
    "Validating...": "正在校验...",
    "Complete!": "完成！",
    "Pulling...": "正在拉取...",
    "Total:": "总计：",
    "Read-only": "只读",
    "built-in": "内置",
    "Gateway:": "网关：",
    "Subnet:": "子网：",
    "Container...": "容器...",
    "Up-to-date": "已是最新",
    "Loading…": "正在加载…",
    "Poll:": "轮询：",
    "Stream:": "流式：",
    "\"All\"": "\"全部\"",
    "\"Any\"": "\"任意\"",
    "Agent:": "代理：",
    "Version:": "版本：",
    "Preview:": "预览：",
    "System:": "系统：",
    "Format:": "格式：",
    "Path:": "路径：",
    "image:tag": "镜像:标签",
    "namespace/image:tag": "命名空间/镜像:标签",
    "Dashboard": "仪表盘",
    "Containers": "容器",
    "Logs": "日志",
    "Shell": "终端",
    "Stacks": "栈",
    "Images": "镜像",
    "Volumes": "卷",
    "Networks": "网络",
    "Registry": "镜像仓库",
    "Registries": "镜像仓库",
    "Activity": "活动",
    "Schedules": "计划任务",
    "Settings": "设置",
    "Backups": "备份",
    "Profile": "个人资料",
    "Users": "用户",
    "Roles": "角色",
    "Security": "安全",
    "General": "常规",
    "Environment": "环境",
    "Environments": "环境",
    "Notifications": "通知",
    "Authentication": "身份验证",
    "License": "许可证",
    "About": "关于",
    "Appearance": "外观",
    "Snapshots": "快照",
    "Favorites": "收藏",
    "Navigation": "导航",
    "Username": "用户名",
    "Password": "密码",
    "Verifying...": "验证中...",
    "Verify": "验证",
    "Admin": "管理员",
    "User": "用户",
    "Enterprise": "企业版",
    "Cancel": "取消",
    "Close": "关闭",
    "Add": "添加",
    "Clear": "清除",
    "Refresh": "刷新",
    "Remove": "移除",
    "Delete": "删除",
    "Edit": "编辑",
    "Create": "创建",
    "Save": "保存",
    "Apply": "应用",
    "OK": "确定",
    "Retry": "重试",
    "Pull": "拉取",
    "Deploy": "部署",
    "Start": "启动",
    "Stop": "停止",
    "Restart": "重启",
    "Pause": "暂停",
    "Unpause": "恢复",
    "Rename": "重命名",
    "Restore": "恢复",
    "Reset": "重置",
    "Download": "下载",
    "Fix": "修复",
    "Test": "测试",
    "Run": "运行",
    "Back": "返回",
    "Next": "下一步",
    "Previous": "上一步",
    "Done": "完成",
    "Select": "选择",
    "Browse": "浏览",
    "Use": "使用",
    "Configure": "配置",
    "Collapse": "折叠",
    "Expand": "展开",
    "Wrap": "换行",
    "Reconnect": "重新连接",
    "Parse": "解析",
    "Export": "导出",
    "Force": "强制",
    "Adopt": "接管",
    "Running": "运行中",
    "running": "运行中",
    "Paused": "已暂停",
    "paused": "已暂停",
    "Restarting": "重启中",
    "restarting": "重启中",
    "Exited": "已退出",
    "exited": "已退出",
    "Created": "创建时间",
    "created": "已创建",
    "Connected": "已连接",
    "Disconnected": "已断开",
    "Offline": "离线",
    "offline": "离线",
    "Enabled": "已启用",
    "Disabled": "已禁用",
    "Failed": "失败",
    "failed": "失败",
    "Success": "成功",
    "Error": "错误",
    "error": "错误",
    "Warning": "警告",
    "Initialized": "已初始化",
    "Checked": "已检查",
    "Unused": "未使用",
    "Live": "实时",
    "All": "全部",
    "None": "无",
    "Never": "从不",
    "Always": "总是",
    "Custom": "自定义",
    "Unknown": "未知",
    "configured": "已配置",
    "Retries": "重试次数",
    "On": "开启",
    "Off": "关闭",
    "Auto": "自动",
    "Blocked": "已屏蔽",
    "Progress": "进度",
    "Trigger": "触发器",
    "days": "天",
    "now": "刚刚",
    "Ready": "就绪",
    "Name": "名称",
    "Value": "值",
    "Key": "键",
    "Labels": "标签",
    "Driver": "驱动",
    "Host": "主机",
    "Status": "状态",
    "Actions": "操作",
    "Action": "操作",
    "Modified": "修改时间",
    "Memory": "内存",
    "CPU": "CPU",
    "CPUs": "CPU",
    "Command": "命令",
    "Image": "镜像",
    "Container": "容器",
    "Volume": "卷",
    "Network": "网络",
    "Port": "端口",
    "Protocol": "协议",
    "Gateway": "网关",
    "Subnet": "子网",
    "Size": "大小",
    "Type": "类型",
    "Mode": "模式",
    "Scope": "作用域",
    "Version": "版本",
    "Platform": "平台",
    "Owner": "所有者",
    "Duration": "时长",
    "Total": "总计",
    "From": "来自",
    "To": "到",
    "Tag": "标签",
    "Repository": "仓库",
    "Branch": "分支",
    "Email": "邮箱",
    "Secret": "密钥",
    "Timestamp": "时间戳",
    "Timezone": "时区",
    "Metadata": "元数据",
    "Expires": "过期时间",
    "Description": "描述",
    "Internal": "内部",
    "Attachable": "可附加",
    "Privileged": "特权",
    "Processes": "进程",
    "Devices": "设备",
    "Capabilities": "功能权限",
    "Config": "配置",
    "Percentage": "百分比",
    "Ulimits": "资源限制",
    "Resources": "资源",
    "System": "系统",
    "Package": "软件包",
    "Socket": "套接字",
    "Bridge": "网桥",
    "Passthru": "直通",
    "Language": "语言",
    "Font": "字体",
    "Daily": "每天",
    "Weekly": "每周",
    "Hourly": "每小时",
    "Monthly": "每月",
    "Stream": "流式",
    "Poll": "轮询",
    "Grid": "网格",
    "Tree": "树状",
    "Circle": "圆形",
    "Radial": "径向",
    "Events": "事件",
    "Templates": "模板",
    "Sources": "模板源",
    "Prune": "清理",
    "Single": "单行",
    "Multi": "多行",
    "Grouped": "已分组",
    "Mem": "内存",
    "Net": "网络",
    "Disk": "磁盘",
    "Validate": "验证",
    "Columns": "列",
    "Exit": "退出",
    "Editor": "编辑器",
    "Graph": "图形",
    "Load": "加载",
    "required": "必填",
    "optional": "可选",
    "Search": "搜索",
    "Connection": "连接",
    "Features": "功能",
    "Version": "版本",
    "Dependencies": "依赖",
    "Partial": "部分运行",
    "Stopped": "已停止",
    "Die": "异常退出",
    "Kill": "强制终止",
    "Destroy": "销毁",
    "Update": "更新",
    "Today": "今天",
    "Yesterday": "昨天",
    "Copy": "复制",
    "Mount": "挂载",
    "Dependency": "依赖",
    "Service": "服务",
    "State": "状态",
    "Health": "健康",
    "healthy": "健康",
    "Uptime": "运行时长",
    "Restarts": "重启次数",
    "Ports": "端口",
    "Stack": "栈",
    "Vulnerabilities": "漏洞",
    "Tags": "标签",
    "Updated": "更新时间",
    "Source": "来源",
    "Location": "位置",
    "Untracked": "未跟踪",
    "Usage": "使用量",
    "Schedule": "计划任务",
    "Secrets": "密钥",
    "ON": "开",
    "OFF": "关",
    "Default": "默认",
    "Normal": "标准",
    "Scheduling": "计划设置",
    "Confirmations": "确认设置",
    "Sunday": "周日",
    "start": "启动",
    "create": "创建",
    "die": "退出",
    "kill": "强制终止",
    "stop": "停止",
    "rename": "重命名",
    "destroy": "销毁",
    "Runtime": "运行时",
    "Database": "数据库",
    "Schema": "模式",
    "Edition": "版本",
    "Community": "社区版",
    "Terms": "服务条款",
    "Privacy": "隐私政策",
    "Cancelled": "已取消",
    "insufficient_scope": "权限不足",
    "invalid_token": "无效令牌",

    // ===================== 登录 (11) =====================
    "Login - Dockhand": "登录 - Dockhand",
    "Dockhand Docker Management": "Dockhand Docker 管理",
    "Welcome back": "欢迎回来",
    "Enter your username": "输入用户名",
    "Enter your password": "输入密码",
    "Two-factor authentication required": "需要双因素认证",
    "Authentication code": "验证码",
    "Enter code": "输入验证码",
    "Enter the 6-digit code from your authenticator app, or use a backup code": "请输入认证器应用中的 6 位验证码，或使用备用码",
    "Back to login": "返回登录",
    "Sign in with": "使用以下方式登录",

    // ===================== 仪表盘 (19) =====================
    "Edit environment settings": "编辑环境设置",
    "Connecting to environment...": "正在连接环境...",
    "Pending updates": "待更新",
    "No metrics available": "暂无可用指标",
    "All containers healthy": "所有容器健康",
    "Recent events": "最近事件",
    "Top containers by CPU": "CPU 占用最高的容器",
    "CPU & Memory history": "CPU 与内存历史",
    "Metrics collection disabled": "指标采集已禁用",
    "Disk usage": "磁盘使用率",
    "Environment offline": "环境离线",
    "Build cache": "构建缓存",
    "No running containers": "无运行中的容器",
    "Paused containers": "已暂停的容器",
    "Restarting containers": "重启中的容器",
    "Running containers": "运行中的容器",
    "Stopped containers": "已停止的容器",
    "Total containers": "容器总数",
    "Unhealthy containers": "不健康的容器",

    // ===================== 容器 (182) =====================
    "Containers - Dockhand": "容器 - Dockhand",
    "Change permissions": "更改权限",
    "Open logs": "查看日志",
    "Rename container": "重命名容器",
    "After restore": "恢复后",
    "Update available": "有可用更新",
    "Device IDs": "设备 ID",
    "Security options": "安全选项",
    "Filter networks...": "筛选网络...",
    "Search containers...": "搜索容器...",
    "No networks found.": "未找到网络。",
    "No shell available": "无可用终端",
    "Container is not running": "容器未运行",
    "Auto-updates not available": "自动更新不可用",
    "Prune containers": "清理容器",
    "Update all containers with available updates": "批量更新所有有可用更新的容器",
    "Disk I/O": "磁盘 I/O",
    "Add another schedule": "添加另一个计划",
    "Add capabilities": "添加能力",
    "Add capability...": "添加能力...",
    "Add device": "添加设备",
    "Add ulimit": "添加 ulimit",
    "Added capabilities": "已添加的能力",
    "Additional networks": "附加网络",
    "Advanced container options (click to expand)": "高级容器选项（点击展开）",
    "After restoring:": "恢复后：",
    "Aliases (comma-separated)": "别名（逗号分隔）",
    "All networks already attached": "所有网络已连接",
    "AppArmor Profile": "AppArmor 配置文件",
    "Apply recursively": "递归应用",
    "Backing up…": "正在备份…",
    "Backup completed": "备份完成",
    "Backup info": "备份信息",
    "Backup log": "备份日志",
    "Backup time": "备份时间",
    "CPU Period/Quota": "CPU 周期/配额",
    "CPU Shares": "CPU 份额",
    "CPU limit": "CPU 限制",
    "CPU period": "CPU 周期",
    "CPU quota": "CPU 配额",
    "CPU shares": "CPU 份额",
    "Cgroup Parent": "Cgroup 父级",
    "Cgroup settings": "Cgroup 设置",
    "Cgroupns Mode": "Cgroupns 模式",
    "Command (optional)": "命令（可选）",
    "Configure a backup": "配置备份",
    "Configure the shell and user for this session": "配置此会话的 shell 和用户",
    "Connected networks": "已连接的网络",
    "Container is paused": "容器已暂停",
    "Container name *": "容器名称 *",
    "Couldn't check the target paths": "无法检查目标路径",
    "Critical/high vulnerabilities found in image": "镜像中发现严重/高危漏洞",
    "Current status": "当前状态",
    "Custom networks": "自定义网络",
    "DNS Options": "DNS 选项",
    "DNS Search": "DNS 搜索",
    "DNS Servers": "DNS 服务器",
    "DNS configuration": "DNS 配置",
    "DNS options": "DNS 选项",
    "DNS search domains": "DNS 搜索域",
    "DNS settings": "DNS 设置",
    "Default (runc)": "默认（runc）",
    "Default security settings": "默认安全设置",
    "Detecting shells...": "正在检测 shell...",
    "Do nothing": "不执行任何操作",
    "Download limit": "下载限制",
    "Drop capabilities": "移除能力",
    "Dropped capabilities": "已移除的能力",
    "Enable GPU access": "启用 GPU 访问",
    "Enable automatic image updates": "启用自动镜像更新",
    "Enable healthcheck": "启用健康检查",
    "Exclude patterns": "排除模式",
    "Exit Code": "退出码",
    "Exposed (internal) port": "暴露（内部）端口",
    "Exposed ports": "暴露端口",
    "Extra hosts": "额外主机",
    "Failing streak": "连续失败次数",
    "Filter labels...": "筛选标签...",
    "Find next available Docker port": "查找下一个可用的 Docker 端口",
    "GPU count": "GPU 数量",
    "GPU mode": "GPU 模式",
    "Image *": "镜像 *",
    "Interval (s)": "间隔（秒）",
    "IPv4 address": "IPv4 地址",
    "IPv6 address": "IPv6 地址",
    "Leave empty for unlimited retries": "留空表示无限重试",
    "Leave host port empty for random allocation": "主机端口留空表示随机分配",
    "Loading container data...": "正在加载容器数据...",
    "Loading files...": "正在加载文件...",
    "Loading log…": "正在加载日志…",
    "Log driver": "日志驱动",
    "MAC address": "MAC 地址",
    "Max retry count": "最大重试次数",
    "Memory Reservation": "内存预留",
    "Memory Swap": "内存交换",
    "Memory limit": "内存限制",
    "Memory reservation": "内存预留",
    "Microseconds per period": "每周期微秒数",
    "No health check configured": "未配置健康检查",
    "No image information available": "无可用镜像信息",
    "No labels": "无标签",
    "No log output was recorded for this run.": "本次运行未记录日志输出。",
    "No metadata available for this snapshot": "此快照无可用元数据",
    "No mounts configured": "未配置挂载",
    "No networks connected.": "未连接网络。",
    "No processes found": "未找到进程",
    "OOM Kill": "OOM 终止",
    "On success": "成功时",
    "Open in new window": "在新窗口打开",
    "Open terminal session": "打开终端会话",
    "Overwrite live": "覆盖实时数据",
    "PIDs Limit": "PID 数限制",
    "Period in microseconds": "周期（微秒）",
    "Port bindings": "端口绑定",
    "Privileged mode": "特权模式",
    "Pull image before update": "更新前拉取镜像",
    "Read-only Root": "只读根",
    "Read-only file (no write permission)": "只读文件（无写权限）",
    "Reading snapshot…": "正在读取快照…",
    "Refresh snapshots": "刷新快照",
    "Replace the live data in place. Destructive.": "就地替换实时数据。此操作具有破坏性。",
    "Resource limits": "资源限制",
    "Restart Count": "重启次数",
    "Restart Policy": "重启策略",
    "Restore completed": "恢复完成",
    "Restore volume data only (skip stack files)": "仅恢复卷数据（跳过栈文件）",
    "Retention policy": "保留策略",
    "Run a backup now, don't save a schedule": "立即运行备份，不保存计划",
    "Runtime name": "运行时名称",
    "Save the schedule and run a backup immediately": "保存计划并立即运行备份",
    "Select a container to share its network namespace": "选择要共享其网络命名空间的容器",
    "Select an environment…": "选择环境…",
    "Select capability to add...": "选择要添加的能力...",
    "Select capability to drop...": "选择要移除的能力...",
    "Select network to add...": "选择要添加的网络...",
    "Show logs": "显示日志",
    "Show terminal": "显示终端",
    "Skip cache directories": "跳过缓存目录",
    "Stack files": "栈文件",
    "Start (s)": "启动（秒）",
    "Start period": "启动周期",
    "State at backup": "备份时的状态",
    "Stop signal": "停止信号",
    "Target environment": "目标环境",
    "This container does not have any shell installed.": "此容器未安装任何 shell。",
    "This container has no shell installed.": "此容器未安装 shell。",
    "Timeout (s)": "超时（秒）",
    "To an environment": "到一个环境",
    "Update selected containers to latest image": "将所选容器更新到最新镜像",
    "Upload files": "上传文件",
    "Upload limit": "上传限制",
    "User Namespace": "用户命名空间",
    "View file": "查看文件",
    "View process list": "查看进程列表",
    "View raw inspect data": "查看原始 inspect 数据",
    "Vulnerability criteria": "漏洞标准",
    "Waiting for first health check to complete...": "等待首次健康检查完成...",
    "Webhook hooks": "Webhook 钩子",
    "Where does it go?": "它去哪了？",
    "Working dir": "工作目录",
    "Block auto-updates if new image has vulnerabilities matching this criteria": "如果新镜像存在匹配此标准的漏洞，则阻止自动更新",
    "Browse, upload, and download files from the container filesystem.": "浏览、上传和下载容器文件系统中的文件。",
    "Clone it onto a chosen environment.": "将其克隆到所选环境。",
    "Close editor": "关闭编辑器",
    "Close viewer": "关闭查看器",
    "DNS &amp; hosts": "DNS 与主机",
    "Dockhand management container": "Dockhand 管理容器",
    "Go to \"Pull\" tab to set the image": "前往\"拉取\"标签页设置镜像",
    "Hawser agents must be updated on their remote host.": "Hawser 代理必须在其远程主机上更新。",
    "Hawser remote agent": "Hawser 远程代理",
    "Health at backup": "备份时的健康状况",
    "Health check log": "健康检查日志",
    "I understand this replaces the live volume data.": "我理解这会替换实时卷数据。",
    "Network I/O": "网络 I/O",
    "New directory": "新建目录",
    "New file": "新建文件",
    "No containers found": "未找到容器",
    "No containers found.": "未找到容器。",
    "No environment variables": "无环境变量",
    "Older snapshots are pruned after each backup. Set 0 to disable.": "每次备份后清理较旧的快照。设为 0 可禁用。",
    "Or enter octal mode directly": "或直接输入八进制模式",
    "Run a backup from the Schedules tab to create one.": "从计划任务标签页运行备份以创建。",

    // ===================== 日志 (34) =====================
    "Logs - Dockhand": "日志 - Dockhand",
    "Clear logs": "清空日志",
    "Copy logs": "复制日志",
    "Download logs": "下载日志",
    "Refresh logs": "刷新日志",
    "Toggle auto-scroll": "切换自动滚动",
    "Toggle word wrap": "切换自动换行",
    "Remove from favorites": "取消收藏",
    "Select for merge": "选择以合并",
    "Connected - Live streaming": "已连接 - 实时流",
    "Streaming paused": "流式传输已暂停",
    "Search logs": "搜索日志",
    "Loading logs...": "正在加载日志...",
    "Number of log lines to load": "要加载的日志行数",
    "Add to favorites": "添加到收藏",
    "Filter containers...": "筛选容器...",
    "Select containers from the list to view merged logs": "请从列表中选择容器以查看合并日志",
    "Click to reconnect": "点击重新连接",
    "Close logs": "关闭日志",
    "Close search": "关闭搜索",
    "Close search (Esc)": "关闭搜索 (Esc)",
    "Connecting to log stream...": "正在连接日志流...",
    "Delete group": "删除分组",
    "Group name...": "分组名称...",
    "Next match": "下一个匹配",
    "Next match (Enter)": "下一个匹配 (Enter)",
    "Previous match": "上一个匹配",
    "Previous match (Shift+Enter)": "上一个匹配 (Shift+Enter)",
    "Save group": "保存分组",
    "Saved groups": "已保存的分组",
    "Search logs (Ctrl+F)": "搜索日志 (Ctrl+F)",
    "Terminal below": "终端在下方",
    "Terminal on side": "终端在侧边",
    "Toggle auto-refresh": "切换自动刷新",

    // ===================== 终端 (11) =====================
    "Terminal - Dockhand": "终端 - Dockhand",
    "Copy output": "复制输出",
    "Clear terminal (Ctrl+L)": "清空终端 (Ctrl+L)",
    "Shell (sh)": "Shell (sh)",
    "Select a container to open shell": "选择容器以打开终端",
    "Ash (Alpine)": "Ash (Alpine)",
    "Clear (Cmd+L)": "清空 (Cmd+L)",
    "Close terminal": "关闭终端",
    "Loading terminal...": "正在加载终端...",
    "No shell available in this container": "此容器无可用 shell",
    "This container may not have a shell installed.": "此容器可能未安装 shell。",

    // ===================== 栈 (127) =====================
    "Stacks - Dockhand": "栈 - Dockhand",
    "What happens when you adopt:": "接管后会发生什么：",
    "None (public)": "无（公开）",
    "External name (optional)": "外部名称（可选）",
    "Environment variable": "环境变量",
    "Stack name": "栈名称",
    "File path": "文件路径",
    "Dockhand host": "Dockhand 主机",
    "Stack already exists": "栈已存在",
    "Down (remove containers)": "停止（移除容器）",
    "Open logs inline": "内嵌打开日志",
    "Open logs in full view": "全屏打开日志",
    "Inspect container": "检查容器",
    "Search stacks...": "搜索栈...",
    "Compose file location unknown. Click the stack name or edit button to locate it.": "Compose 文件位置未知。点击栈名称或编辑按钮以定位。",
    "Env file": "环境变量文件",
    "Browse for compose file": "浏览 compose 文件",
    "Copy path": "复制路径",
    "From Git": "从 Git 部署",
    "Not set": "未设置",
    "(data is unrecoverable)": "（数据不可恢复）",
    "Add new": "新增",
    "Additional env file (optional)": "附加 env 文件（可选）",
    "Additional env file to pass to Docker Compose": "传递给 Docker Compose 的附加 env 文件",
    "Adopt this stack?": "接管此栈？",
    "Always redeploy the stack on webhook or scheduled sync, even if no git changes are detected.": "在 webhook 或计划同步时始终重新部署栈，即使未检测到 git 更改。",
    "Automatically sync repository and redeploy stack if there are changes.": "如有更改，自动同步仓库并重新部署栈。",
    "Build images": "构建镜像",
    "Build images on deploy": "部署时构建镜像",
    "Change location": "更改位置",
    "Check this compose for problems before deploy": "部署前检查此 compose 是否有问题",
    "Checking what can be removed…": "正在检查可移除的内容…",
    "Click a file to select it": "点击文件以选择",
    "Click to select file or folder, double-click to enter folder": "点击选择文件或文件夹，双击进入文件夹",
    "Clone and deploy the stack immediately": "克隆并立即部署栈",
    "Close panel": "关闭面板",
    "Compose Validate": "Compose 校验",
    "Compose file not available": "Compose 文件不可用",
    "Compose file path": "Compose 文件路径",
    "Content (inline)": "内容（内联）",
    "Context directory (optional)": "上下文目录（可选）",
    "Copy URL": "复制 URL",
    "Copy commit hash": "复制提交哈希",
    "Copy repository URL": "复制仓库 URL",
    "Copy secret": "复制密钥",
    "Create folder": "创建文件夹",
    "Defaults to compose file's directory": "默认为 compose 文件所在目录",
    "Defaults to the compose file's parent directory.": "默认为 compose 文件的父目录。",
    "Delete files on disk": "删除磁盘上的文件",
    "Delete named volumes": "删除命名卷",
    "Depends on": "依赖于",
    "Deploy now": "立即部署",
    "Deploy options": "部署选项",
    "Disable build cache": "禁用构建缓存",
    "Dockhand default": "Dockhand 默认",
    "Edit git stack": "编辑 Git 栈",
    "Enable scheduled sync": "启用计划同步",
    "Enable webhook": "启用 webhook",
    "External config": "外部配置",
    "External secret": "外部密钥",
    "External volume": "外部卷",
    "Folder name": "文件夹名称",
    "Force recreate": "强制重建",
    "Force redeployment": "强制重新部署",
    "Generate secret": "生成密钥",
    "Git deploy": "Git 部署",
    "Git · read-only": "Git · 只读",
    "Go up": "向上一层",
    "Leave files": "保留文件",
    "Managed by Dockhand": "由 Dockhand 管理",
    "Move files": "移动文件",
    "Move stack files?": "移动栈文件？",
    "New folder": "新建文件夹",
    "No compose file selected": "未选择 compose 文件",
    "No compose stacks found": "未找到 compose 栈",
    "No containers": "无容器",
    "No problems found": "未发现问题",
    "No repositories configured. Click \"Add new\" to add one.": "未配置仓库。点击\"新增\"添加。",
    "Passes every enabled check.": "通过所有已启用的检查。",
    "Path to the compose file within the repository": "仓库内 compose 文件的路径",
    "Ports (comma-separated)": "端口（逗号分隔）",
    "Pull images": "拉取镜像",
    "Re-pull images": "重新拉取镜像",
    "Recreate (stop & up)": "重建（停止并启动）",
    "Redeploy stack": "重新部署栈",
    "Relocate stack?": "重新定位栈？",
    "Remove connection": "移除连接",
    "Remove dependency": "移除依赖",
    "Remove from recent": "从最近移除",
    "Replace content": "替换内容",
    "Replace editor content?": "替换编辑器内容？",
    "Required - generate or paste a secret": "必填 - 生成或粘贴密钥",
    "Restart stack": "重启栈",
    "Save and close": "保存并关闭",
    "Select a repository...": "选择仓库...",
    "Select existing": "选择现有的",
    "Select stacks to adopt to": "选择要接管到的栈",
    "Specify one of: file or environment": "指定以下之一：文件或环境",
    "Specify one of: file, content, or environment": "指定以下之一：文件、内容或环境",
    "Sync from Git": "从 Git 同步",
    "Sync from git?": "从 Git 同步？",
    "Untracked stack": "未跟踪的栈",
    "This will be the name of the deployed stack": "这将是部署栈的名称",
    "Webhook URL": "Webhook URL",
    "Webhook secret": "Webhook 密钥",
    "What will happen": "将会发生什么",
    "YAML Parse Error": "YAML 解析错误",
    "e.g., my-app": "例如：my-app",
    "e.g., my-stacks": "例如：my-stacks",
    "Always pull latest images before deploying, even if the compose file hasn't changed. Useful for CI/CD workflows with static tags like": "部署前始终拉取最新镜像，即使 compose 文件未更改。适用于使用静态标签的 CI/CD 工作流，如",
    "Browse to locate the compose file for this stack. The editor will load the file contents once selected.": "浏览以定位此栈的 compose 文件。选中后编辑器将加载文件内容。",
    "Choose what to remove. The stack's containers are always stopped and removed.": "选择要移除的内容。栈的容器总是会被停止并移除。",
    "Deploy or sync this Git stack first so Dockhand has a local copy of its compose file.": "请先部署或同步此 Git 栈，以便 Dockhand 拥有其 compose 文件的本地副本。",
    "Dockhand will track these compose files, letting you edit, start, and stop the stacks from the UI. Your files stay in their current location.": "Dockhand 将跟踪这些 compose 文件，让你能从 UI 编辑、启动和停止栈。文件保留在当前位置。",
    "Dockhand will track this compose file, letting you edit, start, and stop the stack from the UI. Your files stay in their current location.": "Dockhand 将跟踪此 compose 文件，让你能从 UI 编辑、启动和停止栈。文件保留在当前位置。",
    "External stack - update possible for individual containers only.": "外部栈 - 仅可更新单个容器。",
    "Image updates available — deploy from Git to apply": "有镜像更新可用 — 从 Git 部署以应用",
    "Loading a different compose file will replace the current editor content.": "加载不同的 compose 文件将替换当前编辑器内容。",
    "Loading compose file...": "正在加载 compose 文件...",
    "No locations yet. Browse folders to add them here.": "尚未添加位置。浏览文件夹以在此添加。",
    "Overrides from the environment variables editor on the right always take highest precedence.": "右侧环境变量编辑器中的覆盖始终具有最高优先级。",
    "Receive push events from your Git provider to trigger sync and redeploy.": "从 Git 提供方接收推送事件以触发同步和重新部署。",
    "Review the compose file before adopting.": "接管前请检查 compose 文件。",
    "Running containers:": "运行中的容器：",
    "The webhook URL will be available after creating the stack.": "创建栈后，webhook URL 将可用。",
    "This is a Git-managed stack — Dockhand shows its compose read-only; edit it in the repository.": "这是一个 Git 管理的栈 — Dockhand 以只读方式显示其 compose；请在仓库中编辑。",
    "Would you like to move all files to the new location, or leave them in place?": "是否要将所有文件移动到新位置，还是保留在原处？",

    // ===================== 镜像 (44) =====================
    "Images - Dockhand": "镜像 - Dockhand",
    "Run container": "运行容器",
    "Scan for vulnerabilities": "扫描漏洞",
    "Tag image": "标记镜像",
    "Push to registry": "推送到镜像仓库",
    "In use": "使用中",
    "Some unused": "部分未使用",
    "Search images...": "搜索镜像...",
    "Prune dangling images": "清理悬空镜像",
    "Prune unused images": "清理未使用镜像",
    "Remove untagged intermediate layers (dangling images)": "删除未标记的中间层（悬空镜像）",
    "Remove ALL images not used by any container (including tagged images)": "删除所有未被任何容器使用的镜像（含已标记镜像）",
    "All images": "全部镜像",
    "All severities": "全部严重级别",
    "All stacks": "全部栈",
    "CSV spreadsheet (.csv)": "CSV 表格 (.csv)",
    "Click \"Scan all images\" to populate this view.": "点击\"扫描全部镜像\"以填充此视图。",
    "Configure a scanner in settings": "在设置中配置扫描器",
    "Export findings": "导出发现",
    "Fixed in": "修复于",
    "Image is up to date": "镜像已是最新",
    "Image layers:": "镜像层：",
    "Images scanned:": "已扫描镜像：",
    "JSON data (.json)": "JSON 数据 (.json)",
    "Layer stack (bottom to top) - click to expand": "层栈（自下而上）- 点击展开",
    "Markdown report (.md)": "Markdown 报告 (.md)",
    "No findings yet": "暂无发现",
    "No fix": "无修复",
    "No images found": "未找到镜像",
    "No layer history found": "未找到层历史",
    "No scan results available": "无可用扫描结果",
    "No vulnerabilities": "无漏洞",
    "No vulnerabilities found.": "未发现漏洞。",
    "No vulnerability scanner is configured for this environment.": "此环境未配置漏洞扫描器。",
    "Preparing scan…": "正在准备扫描…",
    "SARIF (.sarif)": "SARIF (.sarif)",
    "Scan all images": "扫描全部镜像",
    "Search CVE, package, image, container, stack...": "搜索 CVE、软件包、镜像、容器、栈...",
    "Some tags are unused": "部分标签未使用",
    "Total layers:": "总层数：",
    "Total size:": "总大小：",
    "View containers using this image": "查看使用此镜像的容器",
    "View layers": "查看层",
    "Waiting for first result…": "等待首个结果…",

    // ===================== 卷 (24) =====================
    "Volumes - Dockhand": "卷 - Dockhand",
    "Add option": "添加选项",
    "Clone volume": "克隆卷",
    "Value (optional)": "值（可选）",
    "Additional options": "附加选项",
    "Server / IP *": "服务器 / IP *",
    "Search volumes...": "搜索卷...",
    "No driver options configured": "未配置驱动选项",
    "Prune volumes": "清理卷",
    "Browse volume": "浏览卷",
    "Create volume": "创建卷",
    "Enter new volume name": "输入新卷名称",
    "Export path *": "导出路径 *",
    "NFS version": "NFS 版本",
    "New volume name": "新卷名称",
    "No lock": "无锁",
    "No volumes found": "未找到卷",
    "Optional AD/workgroup domain": "可选 AD/工作组域",
    "SMB version": "SMB 版本",
    "Share path *": "共享路径 *",
    "The location on the host where the volume data is stored": "卷数据在主机上的存储位置",
    "Volume driver to use (local is default)": "要使用的卷驱动（默认为 local）",
    "Volume is in use by:": "卷正被以下对象使用：",
    "Volume name *": "卷名称 *",

    // ===================== 网络 (32) =====================
    "Networks - Dockhand": "网络 - Dockhand",
    "Bridge (default)": "网桥（默认）",
    "L2 (default)": "L2（默认）",
    "Prune networks": "清理网络",
    "Connect container": "连接容器",
    "Copy network ID": "复制网络 ID",
    "Duplicate network": "复制网络",
    "View Graph": "查看拓扑图",
    "Allocate container IPs from a sub-range of the subnet": "从子网的子范围分配容器 IP",
    "Allow manual container attachment (overlay networks)": "允许手动连接容器（overlay 网络）",
    "Auxiliary addresses": "辅助地址",
    "Container Id": "容器 ID",
    "Create network": "创建网络",
    "Enable IPv6": "启用 IPv6",
    "Enable IPv6 networking": "启用 IPv6 网络",
    "IP Range:": "IP 范围：",
    "IP range": "IP 范围",
    "IPAM driver": "IPAM 驱动",
    "IPAM options": "IPAM 选项",
    "Network name *": "网络名称 *",
    "No containers available to connect.": "没有可连接的容器。",
    "No containers connected to this network": "没有容器连接到此网络",
    "No networks found": "未找到网络",
    "Parent interface *": "父接口 *",
    "Please fix the validation errors above": "请修复上面的校验错误",
    "Restrict external access to this network": "限制对此网络的外部访问",
    "Search networks...": "搜索网络...",
    "Select a container to connect to this network.": "选择要连接到此网络的容器。",
    "Select a container...": "选择容器...",
    "Subnet *": "子网 *",
    "View network connections between containers": "查看容器之间的网络连接",
    "View network graph": "查看网络拓扑图",

    // ===================== 模板 (8) =====================
    "Add source": "添加源",
    "Configure template catalog sources. Templates are fetched and cached for 1 hour.": "配置模板目录源。模板会被获取并缓存 1 小时。",
    "Disable inactive": "禁用不活跃的",
    "Loading sources...": "正在加载源...",
    "My templates": "我的模板",
    "Refresh templates": "刷新模板",
    "Search templates...": "搜索模板...",
    "Templates - Dockhand": "模板 - Dockhand",

    // ===================== 镜像仓库 (13) =====================
    "Registry - Dockhand": "镜像仓库 - Dockhand",
    "Manage registries": "管理镜像仓库",
    "Copy to another registry": "复制到另一个镜像仓库",
    "Copy to clipboard": "复制到剪贴板",
    "Critical/high vulnerabilities found": "发现严重/高危漏洞",
    "Delete tag": "删除标签",
    "Delete this tag": "删除此标签",
    "Filter results...": "筛选结果...",
    "Loading tags...": "正在加载标签...",
    "No tags found": "未找到标签",
    "Retry pull": "重试拉取",
    "Run container with this tag": "使用此标签运行容器",
    "Start copy": "开始复制",

    // ===================== 活动 (6) =====================
    "Activity - Dockhand": "活动 - Dockhand",
    "Clear all": "全部清除",
    "Container name": "容器名称",
    "Event details": "事件详情",
    "Events will appear here as containers start, stop, etc.": "容器启动、停止等时，事件会显示在这里。",
    "No container events found": "未找到容器事件",

    // ===================== 计划任务 (21) =====================
    "Schedules - Dockhand": "计划任务 - Dockhand",
    "Search schedules...": "搜索计划任务...",
    "Block reason": "阻止原因",
    "Blocked containers": "被阻止的容器",
    "Container updates": "容器更新",
    "Data verify": "数据校验",
    "Delete execution": "删除执行记录",
    "Env update checks": "环境更新检查",
    "Execution history": "执行历史",
    "Git stack syncs": "Git 栈同步",
    "Image prune": "镜像清理",
    "No executions found": "未找到执行记录",
    "No runs": "无运行记录",
    "No schedules found": "未找到计划任务",
    "Remove all": "全部移除",
    "Remove all executions": "移除全部执行记录",
    "Repo check": "仓库检查",
    "Repo prune": "仓库清理",
    "Update block criteria": "更新阻止标准",
    "View last execution logs": "查看上次执行日志",
    "Vulnerability scan results": "漏洞扫描结果",

    // ===================== 备份 (32) =====================
    "All types": "全部类型",
    "All status": "全部状态",
    "All volumes": "全部卷",
    "Backup in progress": "备份进行中",
    "Backup repository": "备份仓库",
    "Backups - Dockhand": "备份 - Dockhand",
    "Comparing snapshots...": "正在比较快照...",
    "Container backup": "容器备份",
    "Copy log content": "复制日志内容",
    "Create backup": "创建备份",
    "Edit backup": "编辑备份",
    "Existing snapshots are kept.": "现有快照将被保留。",
    "Filter backups...": "筛选备份...",
    "Last backup failed": "上次备份失败",
    "Last backup succeeded": "上次备份成功",
    "Loading snapshots…": "正在加载快照…",
    "Loading volumes…": "正在加载卷…",
    "No backup run yet": "尚未运行备份",
    "No backups configured": "未配置备份",
    "No containers or stacks found": "未找到容器或栈",
    "No differences found": "未发现差异",
    "No schedule": "无计划",
    "No schedule — snapshots found in repository": "无计划 — 在仓库中发现快照",
    "No snapshots yet. Run a backup to create one.": "尚无快照。运行备份以创建。",
    "Run backup now": "立即运行备份",
    "Save as recurring schedule": "保存为重复计划",
    "Schedule & run": "计划并运行",
    "Search containers and stacks...": "搜索容器和栈...",
    "Select an environment to see available sources": "选择环境以查看可用来源",
    "Snapshot comparison": "快照比较",
    "Stack backup": "栈备份",
    "Waiting for output…": "等待输出…",

    // ===================== 环境 (6) =====================
    "Paste a full Docker URL to auto-fill the fields below": "粘贴完整 Docker URL 以自动填充下方字段",
    "Production server": "生产服务器",
    "Quick URL (optional)": "快捷 URL（可选）",
    "Edge connection (outbound)": "边缘连接（出站）",
    "TLS certificates (optional)": "TLS 证书（可选）",
    "Testing connection...": "正在测试连接...",

    // ===================== 个人资料 (30) =====================
    "Profile - Dockhand": "个人资料 - Dockhand",
    "Manage your account settings": "管理你的账户设置",
    "Repeat new password": "再次输入新密码",
    "Change password": "修改密码",
    "Managed by your SSO provider": "由你的 SSO 提供商管理",
    "API tokens": "API 令牌",
    "Account information": "账户信息",
    "Change your password": "修改密码",
    "Confirm your password": "确认密码",
    "Copy this token now. It will not be shown again.": "立即复制此令牌。之后不会再显示。",
    "Create tokens for CI/CD pipelines and scripts": "为 CI/CD 流水线和脚本创建令牌",
    "Custom date": "自定义日期",
    "Customize the look of the application": "自定义应用外观",
    "Disable MFA": "禁用 MFA",
    "Enter 6-digit code": "输入 6 位验证码",
    "Enter current password": "输入当前密码",
    "Enter display name": "输入显示名称",
    "Enter email": "输入邮箱",
    "Enter new password": "输入新密码",
    "Generate token": "生成令牌",
    "Last login": "上次登录",
    "Last used": "上次使用",
    "Loading tokens...": "正在加载令牌...",
    "No API tokens created yet.": "尚未创建 API 令牌。",
    "No expiration": "永不过期",
    "Or enter this code manually:": "或手动输入此代码：",
    "Profile details": "个人资料详情",
    "Remove photo": "移除照片",
    "Revoke token": "吊销令牌",
    "Verification code": "验证码",

    // ===================== 审计 (8) =====================
    "Audit log - Dockhand": "审计日志 - Dockhand",
    "Audit log details": "审计日志详情",
    "Entity ID": "实体 ID",
    "Entity name": "实体名称",
    "Entity type": "实体类型",
    "IP address": "IP 地址",
    "No audit log entries found": "未找到审计日志条目",
    "User agent": "用户代理",

    // ===================== 设置-常规 (75) =====================
    "Adopt to:": "接管到：",
    "Show \"What's New\"": "显示\"新功能\"",
    "Show the \"What's New\" popup after upgrading to a new version": "升级到新版本后显示\"新功能\"弹窗",
    "Maximum number of log lines kept per container panel. Older lines are dropped when the limit is exceeded.": "每个容器面板保留的最大日志行数。超出限制时丢弃较早的行。",
    "Format when downloading files from containers or volumes. \"No archive\" emits raw bytes for single files; directories still download as tar.": "从容器或卷下载文件时的格式。\"无归档\"对单文件输出原始字节；目录仍以 tar 下载。",
    "Remove cached vulnerability databases to free disk space. Next scan will re-download fresh data (~200MB).": "删除缓存的漏洞数据库以释放磁盘空间。下次扫描将重新下载全新数据（约 200MB）。",
    "Skip grype and trivy images during \"Prune all unused\"": "在\"清理全部未使用\"时跳过 grype 和 trivy 镜像",
    "Container event cleanup": "容器事件清理",
    "Scanner cache cleanup": "扫描器缓存清理",
    "Schedule execution cleanup": "计划任务执行记录清理",
    "Volume helper cleanup": "卷辅助容器清理",
    "Show stopped containers": "显示已停止的容器",
    "Display stopped and exited containers in lists": "在列表中显示已停止和已退出的容器",
    "Highlight available updates": "高亮可用更新",
    "Highlight container rows in amber when updates are available": "有可用更新时以琥珀色高亮容器行",
    "Show changelog links": "显示更新日志链接",
    "Show a release-notes icon next to images with updates available": "在有可用更新的镜像旁显示更新说明图标",
    "Compact port display": "紧凑端口显示",
    "Show first port with +N count instead of all ports": "仅显示第一个端口并附 +N 计数",
    "Show exposed ports": "显示暴露端口",
    "Display internal container ports in the container list grid": "在容器列表中显示容器内部端口",
    "Show git commit hash": "显示 Git 提交哈希",
    "Display the deployed commit hash on the Git source badge in the stacks list": "在栈列表的 Git 来源徽章上显示部署的提交哈希",
    "Honor Traefik/Pangolin/Caddy labels": "识别 Traefik/Pangolin/Caddy 标签",
    "Show URLs inferred from Traefik and Pangolin labels alongside dockhand.url": "在 dockhand.url 旁显示由 Traefik 和 Pangolin 标签推断的 URL",
    "Time format": "时间格式",
    "Display timestamps in 12-hour (AM/PM) or 24-hour format": "以 12 小时（AM/PM）或 24 小时格式显示时间戳",
    "Date format": "日期格式",
    "How dates are displayed throughout the app": "日期在整个应用中的显示方式",
    "Default timezone": "默认时区",
    "Default timezone for new environments. Used for scheduled tasks like auto-updates.": "新环境的默认时区。用于自动更新等计划任务。",
    "Confirm destructive actions": "破坏性操作需确认",
    "Show confirmation dialogs before deleting resources": "删除资源前显示确认对话框",
    "Logs & files": "日志与文件",
    "Log buffer size": "日志缓冲区大小",
    "Download format": "下载格式",
    "Format log timestamps": "格式化日志时间戳",
    "Convert ISO timestamps in logs to your configured date/time format": "将日志中的 ISO 时间戳转换为配置的日期/时间格式",
    "Compose template": "Compose 模板",
    "Default YAML content when creating a new stack.": "新建栈时的默认 YAML 内容。",
    "Save template": "保存模板",
    "Revert to default": "恢复默认",
    "Vulnerability scanners": "漏洞扫描器",
    "Grype image": "Grype 镜像",
    "Trivy image": "Trivy 镜像",
    "Docker image for Grype scanner. Pin to a specific version for supply chain security.": "Grype 扫描器的 Docker 镜像。固定到特定版本以保障供应链安全。",
    "Docker image for Trivy scanner. Pin to a specific version for supply chain security.": "Trivy 扫描器的 Docker 镜像。固定到特定版本以保障供应链安全。",
    "Default Grype arguments": "默认 Grype 参数",
    "Default Trivy arguments": "默认 Trivy 参数",
    "Scanner cache": "扫描器缓存",
    "Activity event collection mode": "活动事件采集模式",
    "Metrics collection interval": "指标采集间隔",
    "Delete executions older than specified days": "删除超过指定天数的执行记录",
    "Delete events older than specified days": "删除超过指定天数的容器事件",
    "Always enabled": "始终启用",
    "Remove cached vulnerability databases to reclaim disk space": "删除缓存的漏洞数据库以回收磁盘空间",
    "Protect scanner images from prune": "保护扫描器镜像不被清理",
    "Label filter matching": "标签过滤匹配方式",
    "Docker logs use UTC timestamps by default. When enabled, timestamps like": "Docker 日志默认使用 UTC 时间戳。启用后，类似以下的时间戳",
    "are converted to local time using your date/time settings.": "将按你的日期/时间设置转换为本地时间。",
    "Override the Docker network mode for vulnerability scanner containers. Use": "覆盖漏洞扫描容器的 Docker 网络模式。使用",
    "on hosts where the default bridge can't reach the internet (e.g. iptables disabled, SELinux restricted).": "，用于默认 bridge 无法访问互联网的主机（例如 iptables 被禁用、SELinux 受限）。",
    "Adopted stacks": "已接管的栈",
    "Already adopted": "已接管",
    "Apply to all": "应用到全部",
    "Available for adoption": "可接管",
    "Default (auto-detect)": "默认（自动检测）",
    "External stack scan results": "外部栈扫描结果",
    "Not adoptable": "不可接管",
    "Running elsewhere": "在其他地方运行",
    "Scanned paths": "扫描路径",
    "View stacks": "查看栈",
    "Controls how multiple selected labels filter environments on the dashboard.": "控制多个选中标签如何筛选仪表盘上的环境。",
    "Continuous event stream from Docker, instant notifications, higher CPU usage": "Docker 的连续事件流，即时通知，CPU 占用更高",
    "Make sure your paths contain compose.yaml, compose.yml, or similar files.": "确保你的路径中包含 compose.yaml、compose.yml 或类似文件。",
    "No Docker Compose files found in the configured paths.": "配置的路径中未找到 Docker Compose 文件。",
    "Periodic checks for new events, slight notification delay, lower CPU usage": "定期检查新事件，通知略有延迟，CPU 占用更低",

    // ===================== 设置-环境 (97) =====================
    "Delete environment": "删除环境",
    "Copy command": "复制命令",
    "Scan images for known security vulnerabilities": "扫描镜像的已知安全漏洞",
    "Enable scanning": "启用扫描",
    "Choose vulnerability scanner": "选择漏洞扫描器",
    "Run on your host:": "在你的主机上运行：",
    "Not installed": "未安装",
    "Absolute (GB)": "绝对值 (GB)",
    "Channel disabled globally": "通道已被全局禁用",
    "Direct connection": "直连",
    "Unix socket": "Unix socket",
    "Test all": "全部测试",
    "System prune": "清理系统",
    "Prune system": "清理系统",
    "Activity collection will be enabled automatically when you add a channel.": "添加渠道后，活动采集将自动启用。",
    "Add a channel below to receive alerts for this environment": "在下方添加渠道以接收此环境的告警",
    "Add label...": "添加标签...",
    "Add notification channel:": "添加通知渠道：",
    "Agent host": "代理主机",
    "Agent port": "代理端口",
    "Agent token (optional)": "代理令牌（可选）",
    "All unused images": "全部未使用的镜像",
    "Auto-detect Docker socket": "自动检测 Docker socket",
    "Automatic image pruning": "自动清理镜像",
    "Automatic image pruning enabled": "自动清理镜像已启用",
    "Automatically check for container updates on a schedule": "按计划自动检查容器更新",
    "Automatically remove unused Docker images on a schedule to free up disk space.": "按计划自动删除未使用的 Docker 镜像以释放磁盘空间。",
    "Automatically remove unused images on a schedule": "按计划自动删除未使用的镜像",
    "Automatically update containers": "自动更新容器",
    "Block updates with vulnerabilities": "阻止有漏洞的更新",
    "CA certificate (for self-signed)": "CA 证书（用于自签名）",
    "Checking tracked stacks…": "正在检查已跟踪的栈…",
    "Collect CPU and memory usage statistics from this environment": "从此环境采集 CPU 和内存使用统计",
    "Collect container activity": "采集容器活动",
    "Collect system metrics": "采集系统指标",
    "Connection status": "连接状态",
    "Connection token": "连接令牌",
    "Connection type": "连接类型",
    "Copy this token now - you'll need it for the Hawser agent!": "立即复制此令牌 - Hawser 代理需要它！",
    "Copy this token now — it won't be shown again!": "立即复制此令牌 — 之后不会再显示！",
    "Crop icon": "裁剪图标",
    "Dangling images only": "仅悬空镜像",
    "Delete environment?": "删除环境？",
    "Disable certificate validation (insecure)": "禁用证书校验（不安全）",
    "Disk space warnings": "磁盘空间警告",
    "Enable automatic image pruning": "启用自动镜像清理",
    "Enable scheduled update check": "启用计划更新检查",
    "Generate a token now. It will be saved when you add the environment.": "现在生成令牌。添加环境时会保存。",
    "Generate connection token": "生成连接令牌",
    "Generate new token": "生成新令牌",
    "Git-deployed stack": "Git 部署的栈",
    "Go to Settings → Notifications": "前往设置 → 通知",
    "Hawser agent (edge)": "Hawser 代理（边缘）",
    "Hawser agent (standard)": "Hawser 代理（标准）",
    "Hawser edge": "Hawser 边缘",
    "Hawser standard": "Hawser 标准",
    "Highlight value changes": "高亮值变化",
    "Images in use by running or stopped containers will never be removed.": "运行中或已停止的容器正在使用的镜像绝不会被删除。",
    "Last seen:": "上次在线：",
    "Learn more about Hawser": "了解 Hawser 的更多信息",
    "Maximum labels reached": "标签数量已达上限",
    "No containers or stacks found on this environment.": "此环境未找到容器或栈。",
    "No notification channels configured yet.": "尚未配置通知渠道。",
    "No notification channels have been created yet.": "尚未创建通知渠道。",
    "No stacks are currently deployed on this environment, so the rename is safe.": "此环境当前未部署任何栈，因此重命名是安全的。",
    "No stacks are currently tracked on this environment.": "此环境当前未跟踪任何栈。",
    "No token generated yet. Click Generate above.": "尚未生成令牌。点击上方\"生成\"。",
    "Prune mode": "清理模式",
    "Public IP": "公网 IP",
    "Remote stack path (for backup)": "远程栈路径（用于备份）",
    "Remove custom icon": "移除自定义图标",
    "Rename and continue": "重命名并继续",
    "Rename environment?": "重命名环境？",
    "Run Hawser agent on the target host:": "在目标主机上运行 Hawser 代理：",
    "Save the environment first to configure backups.": "请先保存环境以配置备份。",
    "Save this token now - it won't be shown again!": "立即保存此令牌 - 之后不会再显示！",
    "Scheduled update check": "计划更新检查",
    "Skip TLS verification": "跳过 TLS 验证",
    "Socket path": "Socket 路径",
    "Token for agent authentication": "代理认证令牌",
    "Track container events (start, stop, restart, etc.) from this environment in real-time": "实时跟踪此环境的容器事件（启动、停止、重启等）",
    "Untracked stack — can't be backed up until adopted": "未跟踪的栈 — 接管后才能备份",
    "Upload custom icon": "上传自定义图标",
    "Used for clickable port links on the containers page": "用于容器页上可点击的端口链接",
    "Used for scheduling auto-updates, git syncs, and image pruning": "用于计划自动更新、git 同步和镜像清理",
    "Vulnerability scanning": "漏洞扫描",
    "Waiting for agent": "等待代理",
    "Where the agent keeps stack files": "代理存放栈文件的位置",
    "Where this stack's files live on the host": "此栈文件在主机上的位置",
    "Containers will be updated automatically when new images are available.": "当有新镜像可用时，容器将自动更新。",
    "Create notification channels in the Notifications settings tab first.": "请先在通知设置标签页中创建通知渠道。",
    "New images are pulled to a temporary tag, scanned, then deployed if they pass the vulnerability check. Blocked images are deleted automatically.": "新镜像会先拉取到临时标签、扫描，通过漏洞检查后才会部署。被阻止的镜像会自动删除。",
    "Periodically check all containers in this environment for available image updates.": "定期检查此环境中所有容器是否有可用的镜像更新。",
    "Select which notification channels should send alerts for events from this environment.": "选择哪些通知渠道应发送此环境的事件告警。",
    "Send notifications when Docker disk usage exceeds the threshold": "当 Docker 磁盘使用量超过阈值时发送通知",
    "Show amber glow when container values change in the containers list": "当容器列表中的值变化时显示琥珀色高亮",
    "This stack is untracked — Dockhand doesn't know its compose file location, so it can't be backed up. Adopt it (Stacks → Adopt) first.": "此栈未跟踪 — Dockhand 不知道其 compose 文件位置，因此无法备份。请先接管它（栈 → 接管）。",

    // ===================== 设置-标签 (13) =====================
    "Used by": "使用者",
    "Change color": "更改颜色",
    "Current name": "当前名称",
    "Enter new label name": "输入新标签名称",
    "Environment labels": "环境标签",
    "Label name": "标签名称",
    "Loading labels...": "正在加载标签...",
    "No environments available": "无可用环境",
    "No labels found": "未找到标签",
    "Pick a color": "选择颜色",
    "Rename across all environments": "在所有环境中重命名",
    "Rename label": "重命名标签",
    "Reset to default": "恢复默认",

    // ===================== 设置-Git (23) =====================
    "None (public repository)": "无（公开仓库）",
    "A friendly name to identify this credential": "用于标识此凭据的友好名称",
    "A friendly name to identify this repository": "用于标识此仓库的友好名称",
    "Add credential": "添加凭据",
    "Add credentials": "添加凭据",
    "Add repository": "添加仓库",
    "Authentication type": "认证类型",
    "Credential (optional)": "凭据（可选）",
    "Edit repository": "编辑仓库",
    "Git credentials": "Git 凭据",
    "Git repositories": "Git 仓库",
    "Loading credentials...": "正在加载凭据...",
    "Loading repositories...": "正在加载仓库...",
    "Manage Git repositories that can be used to deploy stacks": "管理可用于部署栈的 Git 仓库",
    "Manage credentials for accessing Git repositories": "管理用于访问 Git 仓库的凭据",
    "No Git credentials configured": "未配置 Git 凭据",
    "No Git repositories configured": "未配置 Git 仓库",
    "Passphrase for encrypted key": "加密密钥的密码短语",
    "Password or token": "密码或令牌",
    "Public repository": "公开仓库",
    "SSH passphrase (optional)": "SSH 密码短语（可选）",
    "SSH private key": "SSH 私钥",
    "Username or email": "用户名或邮箱",

    // ===================== 设置-密钥 (4) =====================
    "Add secret provider": "添加密钥提供方",
    "No secret providers": "暂无密钥提供方",
    "Loading secret providers...": "正在加载密钥提供方...",
    "Production secrets": "生产密钥",

    // ===================== 设置-配置集 (7) =====================
    "Invalid port (1-65535)": "端口无效 (1-65535)",
    "What are config sets?": "什么是配置集？",
    "Add config set": "添加配置集",
    "Loading config sets...": "正在加载配置集...",
    "Container port": "容器端口",
    "Host port": "主机端口",
    "No config sets found": "未找到配置集",

    // ===================== 设置-通知 (16) =====================
    "Detailed notification settings (event types, enable/disable) are configured per environment in Environment settings.": "详细的通知设置（事件类型、启用/禁用）在环境设置中按环境配置。",
    "Add channel": "添加渠道",
    "Dockhand Alerts": "Dockhand 告警",
    "From email *": "发件邮箱 *",
    "From name": "发件人名称",
    "Loading notification channels...": "正在加载通知渠道...",
    "My notification channel": "我的通知渠道",
    "Port *": "端口 *",
    "Recipients * (comma-separated)": "收件人 *（逗号分隔）",
    "SMTP (Email)": "SMTP（邮件）",
    "SMTP configuration": "SMTP 配置",
    "SMTP host *": "SMTP 主机 *",
    "Sending test...": "正在发送测试...",
    "Skip TLS verify": "跳过 TLS 验证",
    "Webhook URLs * (one per line)": "Webhook URL *（每行一个）",
    "Webhook configuration": "Webhook 配置",

    // ===================== 设置-认证 (98) =====================
    "Group settings": "分组设置",
    "Confirm password": "确认密码",
    "Add mapping": "添加映射",
    "Copy as new role": "复制为新角色",
    "Enable authentication to configure session settings": "启用身份验证以配置会话设置",
    "Add LDAP": "添加 LDAP",
    "Add provider": "添加提供方",
    "Add role": "添加角色",
    "Add user": "添加用户",
    "Admin group": "管理员组",
    "Admin value(s)": "管理员值",
    "All environments (incl. new)": "所有环境（含新增）",
    "All users have full access to all environments.": "所有用户对所有环境拥有完全访问权限。",
    "Attribute mapping": "属性映射",
    "Base DN": "Base DN",
    "Bind DN": "Bind DN",
    "Bind credentials (optional)": "绑定凭据（可选）",
    "Bind password": "绑定密码",
    "CA certificate (optional)": "CA 证书（可选）",
    "Claim mapping": "声明映射",
    "Claim name": "声明名称",
    "Claim to role mappings": "声明到角色的映射",
    "Claim value": "声明值",
    "Client ID": "客户端 ID",
    "Client credentials": "客户端凭据",
    "Configure group-based access control. These settings are optional.": "配置基于组的访问控制。这些设置是可选的。",
    "Connect to LDAP or Active Directory servers for centralized user authentication.": "连接到 LDAP 或 Active Directory 服务器进行集中式用户认证。",
    "Connection successful": "连接成功",
    "Create a role to define custom permissions": "创建角色以定义自定义权限",
    "Custom roles": "自定义角色",
    "Delete and disable auth": "删除并禁用认证",
    "Delete last admin?": "删除最后一个管理员？",
    "Description (optional)": "描述（可选）",
    "Display name attribute": "显示名称属性",
    "Display name claim": "显示名称声明",
    "Dockhand role": "Dockhand 角色",
    "Edit provider": "编辑提供方",
    "Edit role": "编辑角色",
    "Email attribute": "邮箱属性",
    "Email claim": "邮箱声明",
    "Enable this LDAP configuration": "启用此 LDAP 配置",
    "Enable this OIDC provider": "启用此 OIDC 提供方",
    "Environment permissions": "环境权限",
    "Get these from your identity provider's application settings.": "从你的身份提供方的应用设置中获取这些信息。",
    "Group base DN": "组 Base DN",
    "Group to role mappings": "组到角色的映射",
    "Groups/roles claim": "组/角色声明",
    "How long until inactive sessions expire": "非活动会话多久后过期",
    "Issuer URL": "签发者 URL",
    "LDAP configurations": "LDAP 配置",
    "MFA status": "MFA 状态",
    "Manage user accounts for local authentication, SSO, and LDAP.": "管理本地认证、SSO 和 LDAP 的用户账户。",
    "Map LDAP groups to Dockhand roles. Users in these groups will be assigned the corresponding role.": "将 LDAP 组映射到 Dockhand 角色。这些组中的用户将被分配相应角色。",
    "Map OIDC claims to user attributes.": "将 OIDC 声明映射到用户属性。",
    "Map claim values from your identity provider to Dockhand roles.": "将身份提供方的声明值映射到 Dockhand 角色。",
    "Member filter": "成员过滤器",
    "Members of this group will be admins.": "此组的成员将成为管理员。",
    "Name of the claim containing roles/groups": "包含角色/组的声明名称",
    "No LDAP providers configured": "未配置 LDAP 提供方",
    "No SSO providers configured": "未配置 SSO 提供方",
    "No role mappings configured. Click \"Add mapping\" to create one.": "未配置角色映射。点击\"添加映射\"创建。",
    "No roles configured": "未配置角色",
    "No roles defined yet": "尚未定义角色",
    "No users configured": "未配置用户",
    "Permissions apply to all environments, including future ones.": "权限适用于所有环境，包括未来的环境。",
    "Permissions apply to all environments.": "权限适用于所有环境。",
    "Redirect URI": "重定向 URI",
    "Redirect settings": "重定向设置",
    "Role mapping": "角色映射",
    "Role name": "角色名称",
    "SSO / OIDC": "SSO / OIDC",
    "SSO providers": "SSO 提供方",
    "SSO user - profile synced from identity provider": "SSO 用户 - 个人资料从身份提供方同步",
    "Search users...": "搜索用户...",
    "Server URL": "服务器 URL",
    "Session settings": "会话设置",
    "Session timeout": "会话超时",
    "System permissions": "系统权限",
    "System roles": "系统角色",
    "TLS settings": "TLS 设置",
    "The base DN to search for groups.": "用于搜索组的 Base DN。",
    "The base DN to search for users.": "用于搜索用户的 Base DN。",
    "Upgrade to Enterprise for role-based access control.": "升级到企业版以使用基于角色的访问控制。",
    "User details": "用户详情",
    "User filter": "用户过滤器",
    "User search settings": "用户搜索设置",
    "Username attribute": "用户名属性",
    "Username claim": "用户名声明",
    "Access to development resources": "访问开发资源",
    "Add this URI to your identity provider's allowed callback URLs.": "将此 URI 添加到身份提供方的允许回调 URL 中。",
    "Corporate LDAP": "企业 LDAP",
    "Define roles with granular permissions and assign them to users for access control.": "定义细粒度权限的角色，并将其分配给用户以进行访问控制。",
    "Enable SSO using OpenID Connect providers like Okta, Auth0, Azure AD, or Google Workspace.": "使用 Okta、Auth0、Azure AD 或 Google Workspace 等 OpenID Connect 提供方启用 SSO。",
    "Enable TLS (LDAPS or StartTLS)": "启用 TLS（LDAPS 或 StartTLS）",
    "Grant admin access based on claim values from your identity provider.": "基于身份提供方的声明值授予管理员访问权限。",
    "LDAP / AD": "LDAP / AD",
    "LDAP / Active Directory integration is available with an enterprise license. Connect to your organization's directory services for centralized authentication.": "LDAP / Active Directory 集成需要企业版许可证。连接到组织的目录服务以实现集中式认证。",
    "Select at least one environment for these permissions to be effective.": "至少选择一个环境，这些权限才会生效。",

    // ===================== 设置-许可证 (14) =====================
    "Enter the name exactly as provided with your license": "请输入与许可证上完全一致的名称",
    "Activate your license to validate commercial use.": "激活您的许可证以验证商业用途。",
    "licenses unlock premium features including RBAC, LDAP and audit logs.": "许可证可解锁高级功能，包括基于角色的访问控制（RBAC）、轻量级目录访问协议（LDAP）和审计日志。",
    "License management": "许可证管理",
    "License name": "许可证名称",
    "Your Company Name": "您的公司名称",
    "License key": "许可证密钥",
    "Paste your license key here...": "在此粘贴你的许可证密钥...",
    "Current hostname (for license validation)": "当前主机名（用于许可证验证）",
    "Current hostname": "当前主机名",
    "Deactivate license": "停用许可证",
    "License type": "许可证类型",
    "Licensed host": "授权主机",
    "Loading license information...": "正在加载许可证信息...",

    // ===================== 设置-关于 (22) =====================
    "Checking for updates...": "正在检查更新...",
    "System information": "系统信息",
    "Release notes": "更新说明",
    "Loading releases...": "正在加载更新说明...",
    "Loading dependencies...": "正在加载依赖...",
    "Update check unavailable — click to retry": "检查更新不可用 — 点击重试",
    "Submit issue or idea": "提交问题或建议",
    "Buy me a coffee": "请我喝杯咖啡",
    "Dockhand Community Edition is free and always will be. No strings attached. Like it? Fuel the dev with caffeine.": "Dockhand 社区版永久免费。无任何附加条件。喜欢它？用咖啡支持开发者吧。",
    "Current digest": "当前摘要",
    "Current image": "当前镜像",
    "License terms and conditions": "许可证条款",
    "New digest": "新摘要",
    "New image": "新镜像",
    "Privacy policy": "隐私政策",
    "Search packages or licenses...": "搜索软件包或许可证...",
    "Unix Socket": "Unix Socket",
    "Up to date": "已是最新",
    "Update available — click to see what's new": "有可用更新 — 点击查看新内容",
    "Update now": "立即更新",
    "View on GitHub": "在 GitHub 上查看",
    "What's new": "新功能",

    // ===================== 设置-备份 (37) =====================
    "Rotate repository password": "轮换仓库密码",
    "Needs init": "需要初始化",
    "Passwords do not match": "两次密码不一致",
    "AWS regions": "AWS 区域",
    "AWS regions quick pick": "AWS 区域快速选择",
    "Add destination": "添加目标",
    "Auto-unlock stale locks": "自动解锁过期锁",
    "Automatically removes stale repository locks before prune and check operations. Locks can be left behind by interrupted or crashed backups.": "在执行清理和检查操作前自动移除过期的仓库锁。锁可能由中断或崩溃的备份遗留。",
    "Backend type": "后端类型",
    "Backup helper image": "备份辅助镜像",
    "Browse snapshot content": "浏览快照内容",
    "Browse snapshots": "浏览快照",
    "Check integrity": "检查完整性",
    "Confirm new password": "确认新密码",
    "Copy password": "复制密码",
    "Data %": "数据 %",
    "Edit destination": "编辑目标",
    "Encryption password": "加密密码",
    "Extra backup flags": "额外备份参数",
    "Extra restore flags": "额外恢复参数",
    "Filter by environment...": "按环境筛选...",
    "Filter destinations...": "筛选目标...",
    "Generate strong password": "生成强密码",
    "Initialize repository": "初始化仓库",
    "Limit download speed to 10 MB/s": "将下载速度限制为 10 MB/s",
    "Limit upload speed to 5 MB/s": "将上传速度限制为 5 MB/s",
    "Loading backup destinations...": "正在加载备份目标...",
    "Loading repository stats...": "正在加载仓库统计...",
    "Loading snapshots...": "正在加载快照...",
    "Max unused %": "最大未使用 %",
    "Maximum compression": "最大压缩",
    "New password must differ from current": "新密码必须与当前密码不同",
    "No backup destinations": "无备份目标",
    "No snapshots in this repository.": "此仓库中无快照。",
    "Prune unused data": "清理未使用的数据",
    "Repair index": "修复索引",
    "Repository policies": "仓库策略",

    // ===================== 设置-镜像仓库 (7) =====================
    "Add registry": "添加镜像仓库",
    "Test connectivity": "测试连接",
    "Loading registries...": "正在加载镜像仓库...",
    "My Private Registry": "我的私有镜像仓库",
    "No registries found": "未找到镜像仓库",
    "Password / Token": "密码 / 令牌",
    "Set default": "设为默认",

    // ===================== 共享组件 (113) =====================
    "Sign out": "退出登录",
    "View profile": "查看个人资料",
    "Copy error": "复制错误",
    "Toggle Sidebar": "切换侧边栏",
    "Collapse sidebar": "折叠侧边栏",
    "Expand sidebar": "展开侧边栏",
    "Toggle theme": "切换主题",
    "Toggle log theme": "切换日志主题",
    "Customize menu": "自定义菜单",
    "Keep image": "保留镜像",
    "None — disabled": "无 — 已禁用",
    "Never block": "从不屏蔽",
    "Image name": "镜像名称",
    "Command Palette": "命令面板",
    "No environments": "暂无环境",
    "No results found.": "未找到结果。",
    "Dockhand update available": "Dockhand 有可用更新",
    "Critical only": "仅严重",
    "Critical or high": "严重或高危",
    "Any vulnerabilities": "任意漏洞",
    "More than current image": "多于当前镜像",
    "Switch environment": "切换环境",
    "Select environment": "选择环境",
    "Light theme": "浅色主题",
    "Dark theme": "深色主题",
    "Check for available updates": "检查可用更新",
    "required w/ error": "必填且有错误",
    "No environment variables defined.": "未定义环境变量。",
    "Add your first variable": "添加第一个变量",
    "Form view": "表单视图",
    "Text view (raw .env file)": "文本视图（原始 .env 文件）",
    "Clear all variables?": "清除全部变量？",
    "Column settings": "列设置",
    "Daemon hostname / IP": "守护进程主机名 / IP",
    "Font size": "字号",
    "Grid font size": "表格字号",
    "Grid buttons": "表格按钮",
    "Terminal font": "终端字体",
    "Editor font": "编辑器字体",
    "Colored grid buttons": "彩色表格按钮",
    "Use semantic colors instead of muted gray": "使用语义颜色替代暗灰色",
    "Animate icons": "图标动画",
    "Spinners during pulls, scans and updates.": "拉取、扫描和更新期间显示加载动画。",
    "Indentation guides": "缩进参考线",
    "Vertical guides showing nesting depth in the code editor.": "在代码编辑器中显示嵌套深度的垂直参考线。",
    "Open the app on": "应用打开于",
    "Where the app opens (on the last-used environment).": "应用打开时使用的环境（上次使用的环境）。",
    "Environment click": "环境点击行为",
    "Where a tile click goes.": "点击环境磁贴后的跳转位置。",
    "Got it": "知道了",
    "All timezones": "全部时区",
    "Backup failed": "备份失败",
    "Check for newer version tags": "检查是否有更新版本标签",
    "Click for release notes. Never auto-applied.": "点击查看发布说明。绝不会自动应用。",
    "Displays the mobile sidebar.": "显示移动端侧边栏。",
    "Drag to reorder (or use arrow keys)": "拖动以重新排序（或使用方向键）",
    "Drag to reposition. Use the slider to zoom.": "拖动以重新定位。使用滑块缩放。",
    "Enter an image name to start pulling": "输入镜像名称以开始拉取",
    "From env file in repository": "来自仓库中的 env 文件",
    "Full image reference": "完整镜像引用",
    "Include prereleases": "包含预发布版本",
    "Layer ID": "层 ID",
    "Match the tag flavor": "匹配标签风格",
    "Move to": "移动到",
    "Newer version available": "有更新版本可用",
    "No backup runs yet.": "暂无备份运行记录。",
    "No changes recorded": "未记录到更改",
    "No environment configured": "未配置环境",
    "No environment selected": "未选择环境",
    "No icons found": "未找到图标",
    "No timezone found.": "未找到时区。",
    "No vulnerabilities!": "无漏洞！",
    "Only suggest tags with the same suffix as the one you run — the flavor, like": "仅建议与你运行的标签具有相同后缀的标签 — 即风格，如",
    "Open on GitHub": "在 GitHub 上打开",
    "Optional variable (has default)": "可选变量（有默认值）",
    "Probing the host for the stack folder...": "正在探测主机上的栈文件夹...",
    "Pull completed!": "拉取完成！",
    "Pulling layers...": "正在拉取层...",
    "Push complete!": "推送完成！",
    "Push failed": "推送失败",
    "Ready to push to": "准备推送到",
    "Ready to scan": "准备扫描",
    "Required variable defined": "必填变量已定义",
    "Reset menu to default order and visibility": "将菜单重置为默认顺序和可见性",
    "Reset to defaults": "恢复默认",
    "Run a backup — its history appears here.": "运行一次备份 — 其历史记录会显示在这里。",
    "Scan failed": "扫描失败",
    "Scanning for vulnerabilities...": "正在扫描漏洞...",
    "Search icons...": "搜索图标...",
    "Search timezone...": "搜索时区...",
    "Secret provider": "密钥提供方",
    "Secret value (cannot unhide)": "密钥值（无法重新显示）",
    "Some lines couldn't be parsed:": "部分行无法解析：",
    "Some vulnerabilities found": "发现部分漏洞",
    "Stack files on the host": "主机上的栈文件",
    "Start scan": "开始扫描",
    "Switch to text view to edit these lines.": "切换到文本视图以编辑这些行。",
    "Unused variable": "未使用的变量",
    "Use global default": "使用全局默认",
    "View log": "查看日志",
    "Vulnerabilities found": "发现漏洞",
    "Where this path comes from": "此路径的来源",
    "Which updates to show": "显示哪些更新",
    "A local-path repo only works if this environment's Docker daemon is on the same host as Dockhand.": "本地路径仓库仅在此环境的 Docker 守护进程与 Dockhand 位于同一主机时有效。",
    "Advisory only. Dockhand never changes the tag in your compose - bump it yourself.": "仅作参考。Dockhand 绝不会更改你 compose 中的标签 - 请自行提升。",
    "Captured from the host at": "从主机捕获于",
    "Contents are captured in the snapshot, but bind sources are host paths. Restoring to a different environment requires those exact paths on the target host — otherwise services start with empty mounts.": "内容已捕获到快照中，但绑定源是主机路径。恢复到不同环境需要目标主机上有完全相同的路径 — 否则服务将以空挂载启动。",
    "Injected into the container at last deploy &mdash; never written to": "在最后一次部署时注入容器 — 绝不会写入",
    "It is derived from the stack's bind mounts. To set it explicitly, use": "它源自栈的绑定挂载。要显式设置，请使用",
    "No stack folder found on the host": "主机上未找到栈文件夹",
    "Secrets are never written to disk and are injected via shell environment when the stack starts.": "密钥绝不会写入磁盘，而是在栈启动时通过 shell 环境注入。",
    "These variables are available for": "这些变量可用于",
    "Update available:": "有可用更新：",

    // ===================== 成功提示 (50) =====================
    "Settings saved": "设置已保存",
    "Schedule saved": "计划任务已保存",
    "Schedule retention updated": "计划任务保留策略已更新",
    "User created": "用户已创建",
    "User updated": "用户已更新",
    "User deleted": "用户已删除",
    "Snapshot deleted": "快照已删除",
    "Repository deleted": "仓库已删除",
    "Registry deleted": "镜像仓库已删除",
    "Role deleted": "角色已删除",
    "Renamed successfully": "重命名成功",
    "Test notification sent successfully": "测试通知发送成功",
    "Token generated successfully": "令牌生成成功",
    "Unused volumes pruned": "已清理未使用的卷",
    "Unused networks pruned": "已清理未使用的网络",
    "Trivy image updated": "Trivy 镜像已更新",
    "Trivy default arguments updated": "Trivy 默认参数已更新",
    "Scanner cleanup cron updated": "扫描器清理定时任务已更新",
    "Source added": "已添加源",
    "Source removed": "已移除源",
    "Repository fields are incomplete": "仓库字段不完整",
    "Activity log cleared": "活动日志已清除",
    "All containers are up to date": "所有容器均为最新",
    "Backup image updated": "备份镜像已更新",
    "Backup schedule removed": "备份计划已移除",
    "Compose template updated": "Compose 模板已更新",
    "Config set deleted": "配置集已删除",
    "Container created successfully": "容器创建成功",
    "Container removed": "容器已移除",
    "Copied to clipboard": "已复制到剪贴板",
    "Credential deleted": "凭据已删除",
    "Default registry updated": "默认镜像仓库已更新",
    "Destination deleted": "目标已删除",
    "Event cleanup cron updated": "事件清理定时任务已更新",
    "Event retention updated": "事件保留策略已更新",
    "Execution deleted": "执行记录已删除",
    "File saved": "文件已保存",
    "Grype default arguments updated": "Grype 默认参数已更新",
    "Grype image updated": "Grype 镜像已更新",
    "LDAP configuration deleted": "LDAP 配置已删除",
    "License activated successfully": "许可证激活成功",
    "License deactivated": "许可证已停用",
    "Live updates reconnected": "实时更新已重连",
    "Log buffer size updated": "日志缓冲区大小已更新",
    "Network ID copied to clipboard": "网络 ID 已复制到剪贴板",
    "New image tag copied": "新镜像标签已复制",
    "Notification channel added": "通知渠道已添加",
    "Notification channel deleted": "通知渠道已删除",
    "OIDC provider deleted": "OIDC 提供商已删除",
    "Secret provider deleted": "密钥提供方已删除",

    // ===================== 错误提示 (68) =====================
    "Login failed": "登录失败",
    "An unexpected error occurred": "发生意外错误",
    "Failed to initiate SSO login": "无法发起 SSO 登录",
    "Failed to save": "保存失败",
    "Failed to save settings": "保存设置失败",
    "Failed to delete": "删除失败",
    "Failed to update schedule": "更新计划任务失败",
    "Failed to load snapshots": "加载快照失败",
    "Failed to load env variables": "加载环境变量失败",
    "Failed to fetch git credentials": "获取 Git 凭据失败",
    "Failed to prune volumes": "清理卷失败",
    "Failed to prune networks": "清理网络失败",
    "Connection test failed": "连接测试失败",
    "Init failed": "初始化失败",
    "Failed to toggle notification channel": "切换通知渠道失败",
    "Failed to toggle OIDC provider": "切换 OIDC 提供商失败",
    "Failed to toggle LDAP configuration": "切换 LDAP 配置失败",
    "Failed to set default registry": "设置默认镜像仓库失败",
    "Failed to save navigation preference": "保存导航偏好失败",
    "Failed to delete snapshot": "删除快照失败",
    "Failed to delete role": "删除角色失败",
    "Failed to delete repository": "删除仓库失败",
    "Failed to delete credential": "删除凭据失败",
    "Failed to delete OIDC provider": "删除 OIDC 提供商失败",
    "Failed to delete LDAP configuration": "删除 LDAP 配置失败",
    "Failed to clear update indicators": "清除更新提示失败",
    "Repository connection successful": "仓库连接成功",
    "OIDC connection successful": "OIDC 连接成功",
    "Could not query registry": "无法查询镜像仓库",
    "Check failed: ": "检查失败：",
    "Connection failed - click refresh to retry": "连接失败 - 点击刷新重试",
    "Connection failed. Click to retry.": "连接失败。点击重试。",
    "Connection lost: ": "连接丢失：",
    "Connection timed out": "连接超时",
    "Could not find image to push": "找不到要推送的镜像",
    "Could not reach the server to check the target paths.": "无法访问服务器以检查目标路径。",
    "Failed to activate license": "激活许可证失败",
    "Failed to browse registry": "浏览镜像仓库失败",
    "Failed to change password": "修改密码失败",
    "Failed to check for updates": "检查更新失败",
    "Failed to create environment": "创建环境失败",
    "Failed to create token": "创建令牌失败",
    "Failed to create user": "创建用户失败",
    "Failed to fetch logs: ": "获取日志失败：",
    "Failed to fetch processes": "获取进程失败",
    "Failed to load container data: ": "加载容器数据失败：",
    "Failed to load metadata": "加载元数据失败",
    "Failed to load profile": "加载个人资料失败",
    "Failed to read the snapshot": "读取快照失败",
    "Failed to remove avatar": "删除头像失败",
    "Failed to save credential": "保存凭据失败",
    "Failed to save git stack": "保存 Git 栈失败",
    "Failed to save repository": "保存仓库失败",
    "Failed to search images": "搜索镜像失败",
    "Failed to setup MFA": "设置 MFA 失败",
    "Failed to start backup": "启动备份失败",
    "Failed to start streaming": "启动流式传输失败",
    "Failed to test notification": "测试通知失败",
    "Failed to update container: ": "更新容器失败：",
    "Failed to update environment": "更新环境失败",
    "Failed to update profile": "更新个人资料失败",
    "Failed to update user": "更新用户失败",
    "Failed to upload avatar": "上传头像失败",
    "Failed to verify MFA": "验证 MFA 失败",
    "No response body": "无响应内容",
    "Connection test successful": "连接测试成功",
    "Connection works": "连接正常",
    "Edge mode - connection will be tested when agent connects": "边缘模式 - 代理连接时将测试连接",

    // ===================== 校验提示 (221) =====================
    "Name is required": "名称为必填项",
    "Schedule is invalid": "计划任务无效",
    "Required variable (defined)": "必填变量（已定义）",
    "All fields are required": "所有字段均为必填项",
    "At least one webhook URL is required": "至少需要一个 webhook URL",
    "Host, from email, and at least one recipient are required": "主机、发件邮箱和至少一个收件人为必填项",
    "Name and URL are required": "名称和 URL 为必填项",
    "Name and host are required": "名称和主机为必填项",
    "Name and license key are required": "名称和许可证密钥为必填项",
    "Password is required": "密码为必填项",
    "Password must be at least 8 characters": "密码至少 8 个字符",
    "Token name is required": "令牌名称为必填项",
    "URL is required to test": "测试需要 URL",
    "Invalid 1Password Connect token": "1Password Connect 令牌无效",
    "Invalid Apprise URL format - missing protocol": "Apprise URL 格式无效 - 缺少协议",
    "Invalid Apprise URL. Expected: apprise://host[:port]/key": "Apprise URL 无效。期望格式：apprise://host[:port]/key",
    "Invalid CPU limit (e.g. 0.5, 1.5, 2)": "CPU 限制无效（例如 0.5、1.5、2）",
    "Invalid CPU period": "CPU 周期无效",
    "Invalid CPU quota": "CPU 配额无效",
    "Invalid CPU shares": "CPU 份额无效",
    "Invalid Docker API path": "Docker API 路径无效",
    "Invalid Gotify URL format. Expected: gotify://hostname/token": "Gotify URL 格式无效。期望：gotify://hostname/token",
    "Invalid ID token": "ID 令牌无效",
    "Invalid ID": "ID 无效",
    "Invalid IP address": "IP 地址无效",
    "Invalid IPv4 address": "IPv4 地址无效",
    "Invalid IPv6 address": "IPv6 地址无效",
    "Invalid JSON body": "JSON 正文无效",
    "Invalid MAC address (e.g., 02:42:ac:11:00:02)": "MAC 地址无效（例如 02:42:ac:11:00:02）",
    "Invalid MFA code": "MFA 验证码无效",
    "Invalid Mattermost URL format. Expected: mmost://[botname@]hostname[:port][/path]/token": "Mattermost URL 格式无效。期望：mmost://[botname@]hostname[:port][/path]/token",
    "Invalid Pushover URL format. Expected: pushover://user_key/api_token": "Pushover URL 格式无效。期望：pushover://user_key/api_token",
    "Invalid Signal URL. Expected: signal://host[:port]/+source/+target1[/+target2/...]": "Signal URL 无效。期望：signal://host[:port]/+source/+target1[/+target2/...]",
    "Invalid URL format": "URL 格式无效",
    "Invalid Workflows URL format. Expected: workflows://hostname/workflow/signature": "Workflows URL 格式无效。期望：workflows://hostname/workflow/signature",
    "Invalid YAML": "YAML 无效",
    "Invalid action. Use \"rename\", \"delete\", \"add\", or \"set-color\"": "操作无效。请使用 \"rename\"、\"delete\"、\"add\" 或 \"set-color\"",
    "Invalid actionIconSize": "actionIconSize 无效",
    "Invalid animateIcons": "animateIcons 无效",
    "Invalid auth type": "认证类型无效",
    "Invalid branch/ref name": "分支/引用名无效",
    "Invalid chmod mode": "chmod 模式无效",
    "Invalid coloredActionButtons": "coloredActionButtons 无效",
    "Invalid configId": "configId 无效",
    "Invalid configuration ID": "配置 ID 无效",
    "Invalid credential ID": "凭据 ID 无效",
    "Invalid dark theme": "dark theme 无效",
    "Invalid destination ID": "目标 ID 无效",
    "Invalid destinationId": "destinationId 无效",
    "Invalid editor font": "编辑器字体无效",
    "Invalid editorIndentGuides": "editorIndentGuides 无效",
    "Invalid env path": "环境变量路径无效",
    "Invalid env": "环境变量无效",
    "Invalid envClickPage": "envClickPage 无效",
    "Invalid environment ID": "环境 ID 无效",
    "Invalid execution ID": "执行 ID 无效",
    "Invalid expiration date": "过期日期无效",
    "Invalid file path": "文件路径无效",
    "Invalid font size": "字号无效",
    "Invalid font": "字体无效",
    "Invalid grid font size": "表格字号无效",
    "Invalid hideSystemJobs (must be boolean)": "hideSystemJobs 无效（必须为布尔值）",
    "Invalid image format": "镜像格式无效",
    "Invalid landingPage": "landingPage 无效",
    "Invalid license format": "许可证格式无效",
    "Invalid license signature": "许可证签名无效",
    "Invalid light theme": "light theme 无效",
    "Invalid memory value (e.g. 512m, 1g)": "内存值无效（例如 512m、1g）",
    "Invalid memory value": "内存值无效",
    "Invalid nonce": "nonce 无效",
    "Invalid or expired state": "状态无效或已过期",
    "Invalid password": "密码无效",
    "Invalid path": "路径无效",
    "Invalid policies JSON": "策略 JSON 无效",
    "Invalid port number": "端口号无效",
    "Invalid registry ID": "镜像仓库 ID 无效",
    "Invalid repository ID": "仓库 ID 无效",
    "Invalid repository URL": "仓库 URL 无效",
    "Invalid request body": "请求正文无效",
    "Invalid request body: content string required": "请求正文无效：需要 content 字符串",
    "Invalid request body: variables array required": "请求正文无效：需要 variables 数组",
    "Invalid request": "请求无效",
    "Invalid restic flags": "restic 参数无效",
    "Invalid restore request": "恢复请求无效",
    "Invalid scanner type": "扫描器类型无效",
    "Invalid schedule ID": "计划任务 ID 无效",
    "Invalid schedule type": "计划任务类型无效",
    "Invalid secret provider ID": "密钥提供方 ID 无效",
    "Invalid snapshot ID": "快照 ID 无效",
    "Invalid snapshotId": "snapshotId 无效",
    "Invalid stack ID": "栈 ID 无效",
    "Invalid stack data: missing name or composePath": "栈数据无效：缺少 name 或 composePath",
    "Invalid string length": "字符串长度无效",
    "Invalid system schedule ID": "系统计划任务 ID 无效",
    "Invalid targetName": "targetName 无效",
    "Invalid terminal font": "终端字体无效",
    "Invalid timezone": "时区无效",
    "Invalid token ID": "令牌 ID 无效",
    "Invalid token": "令牌无效",
    "Invalid username or password": "用户名或密码无效",
    "Invalid variable: key is required and must be a string": "变量无效：key 为必填且必须是字符串",
    "Invalid verification code": "验证码无效",
    "Invalid webhook secret": "webhook 密钥无效",
    "Invalid webhook signature": "webhook 签名无效",
    "A valid provider type is required": "需要有效的提供方类型",
    "A webhook secret is required when the webhook is enabled": "启用 webhook 时需要 webhook 密钥",
    "Avatar data is required": "头像数据为必填项",
    "Base DN is required": "Base DN 为必填项",
    "Client ID is required when a client secret is set": "设置客户端密钥时需要客户端 ID",
    "Client ID is required": "客户端 ID 为必填项",
    "Client secret is required when a client ID is set": "设置客户端 ID 时需要客户端密钥",
    "Client secret is required": "客户端密钥为必填项",
    "Compose file content is required": "Compose 文件内容为必填项",
    "Compose file content or path is required": "Compose 文件内容或路径为必填项",
    "Compose path is required": "Compose 路径为必填项",
    "Config is required": "配置为必填项",
    "Container ID is required": "容器 ID 为必填项",
    "Container name is required": "容器名称为必填项",
    "Content is required": "内容为必填项",
    "Current password is required": "当前密码为必填项",
    "Either repositoryId or url is required": "需要 repositoryId 或 url",
    "Environment ID is required": "环境 ID 为必填项",
    "Export path is required": "导出路径为必填项",
    "File path is required": "文件路径为必填项",
    "Group name is required": "组名称为必填项",
    "Host is required for this connection type": "此连接类型需要主机",
    "Host is required": "主机为必填项",
    "Image name is required": "镜像名称为必填项",
    "Issuer URL is required": "签发者 URL 为必填项",
    "MFA token is required": "MFA 令牌为必填项",
    "Mode is required (e.g., \"755\" or \"u+x\")": "模式为必填项（例如 \"755\" 或 \"u+x\"）",
    "Mode is required": "模式为必填项",
    "Network name is required": "网络名称为必填项",
    "New name is required": "新名称为必填项",
    "New path is required": "新路径为必填项",
    "New volume name is required": "新卷名称为必填项",
    "Old path is required": "旧路径为必填项",
    "Password is required for password authentication": "密码认证需要密码",
    "Password is required to create an API token": "创建 API 令牌需要密码",
    "Path is required": "路径为必填项",
    "Redirect URI is required": "重定向 URI 为必填项",
    "Registry ID is required": "镜像仓库 ID 为必填项",
    "Repository URL is required to test": "测试需要仓库 URL",
    "Repository URL is required": "仓库 URL 为必填项",
    "Repository URL or existing repository ID is required": "需要仓库 URL 或已有的仓库 ID",
    "Repository name is required": "仓库名称为必填项",
    "Request body (an image tar) is required": "需要请求正文（镜像 tar）",
    "Role ID is required": "角色 ID 为必填项",
    "Role name is required": "角色名称为必填项",
    "SSH private key is required for SSH authentication": "SSH 认证需要 SSH 私钥",
    "SSH private key is required": "SSH 私钥为必填项",
    "Search term is required": "搜索词为必填项",
    "Server URL is required": "服务器 URL 为必填项",
    "Server is required": "服务器为必填项",
    "Share path is required": "共享路径为必填项",
    "Stack name is required": "栈名称为必填项",
    "Tag is required": "标签为必填项",
    "Target path is required": "目标路径为必填项",
    "Template is required": "模板为必填项",
    "Token ID is required": "令牌 ID 为必填项",
    "Token name must be 255 characters or less": "令牌名称不能超过 255 个字符",
    "URL is required": "URL 为必填项",
    "User ID is required": "用户 ID 为必填项",
    "Username is required": "用户名为必填项",
    "Volume name is required": "卷名称为必填项",
    "Zabbix API token is required": "Zabbix API 令牌为必填项",
    "Zabbix host is required": "Zabbix 主机为必填项",
    "Zabbix item key is required": "Zabbix 监控项键为必填项",
    "Action must be \"add\", \"remove\", \"update\", or \"reorder\"": "操作必须为 \"add\"、\"remove\"、\"update\" 或 \"reorder\"",
    "Action must be \"add\", \"remove\", or \"reorder\"": "操作必须为 \"add\"、\"remove\" 或 \"reorder\"",
    "Bitwarden Project selector must be a valid UUID": "Bitwarden 项目选择器必须是有效的 UUID",
    "Bitwarden bws command exceeded the stderr limit": "Bitwarden bws 命令超出 stderr 限制",
    "Bitwarden bws command exceeded the stdout limit": "Bitwarden bws 命令超出 stdout 限制",
    "Bitwarden bws executable path must be absolute": "Bitwarden bws 可执行文件路径必须是绝对路径",
    "Bitwarden bws version must be >=2.1.0 and <3.0.0": "Bitwarden bws 版本必须 >=2.1.0 且 <3.0.0",
    "Cannot access path": "无法访问路径",
    "Cannot auto-update Dockhand itself": "无法自动更新 Dockhand 自身",
    "Cannot auto-update Hawser agent": "无法自动更新 Hawser 代理",
    "Cannot change the destination while a backup is running for this config": "此配置正在备份，无法更改目标",
    "Cannot delete critical system path": "无法删除关键系统路径",
    "Cannot delete environment with empty name": "无法删除名称为空的环境",
    "Cannot delete image: it has dependent child images. Delete those first or use force delete.": "无法删除镜像：它存在依赖的子镜像。请先删除子镜像或使用强制删除。",
    "Cannot delete image: it is being used by a running container. Stop the container first.": "无法删除镜像：它正被运行中的容器使用。请先停止该容器。",
    "Cannot delete system roles": "无法删除系统角色",
    "Cannot delete this environment": "无法删除此环境",
    "Cannot enable authentication without any users. Create a user first.": "没有任何用户时无法启用身份验证。请先创建用户。",
    "Cannot modify an admin account": "无法修改管理员账户",
    "Cannot modify system roles": "无法修改系统角色",
    "Cannot read a directory": "无法读取目录",
    "Cannot write masked placeholder \"***\" to .env file - this would corrupt secret values": "无法将掩码占位符 \"***\" 写入 .env 文件 - 这会破坏密钥值",
    "Compose file must be a YAML mapping at the top level": "Compose 文件顶层必须是 YAML 映射",
    "Compose file must be within the context directory": "Compose 文件必须位于上下文目录内",
    "Config must be an object": "配置必须是对象",
    "Containers array is required and must not be empty": "容器数组为必填且不能为空",
    "Context directory must be within the repository": "上下文目录必须位于仓库内",
    "Current password does not match": "当前密码不匹配",
    "Directory is not empty": "目录不为空",
    "Docker disk usage exceeds threshold": "Docker 磁盘使用量超过阈值",
    "Event poll interval must be between 30s and 300s": "事件轮询间隔必须在 30 秒到 300 秒之间",
    "Expiration date must be in the future": "过期日期必须在未来",
    "Image is in use and cannot be deleted": "镜像正在使用中，无法删除",
    "Metrics collection interval must be between 10s and 300s": "指标采集间隔必须在 10 秒到 300 秒之间",
    "Name cannot be empty": "名称不能为空",
    "New label cannot be empty": "新标签不能为空",
    "New password must be at least 8 characters": "新密码至少 8 个字符",
    "Path must be absolute": "路径必须是绝对路径",
    "Proton Pass pass-cli command exceeded the stderr limit": "Proton Pass pass-cli 命令超出 stderr 限制",
    "Proton Pass pass-cli command exceeded the stdout limit": "Proton Pass pass-cli 命令超出 stdout 限制",
    "Proton Pass pass-cli executable path must be absolute": "Proton Pass pass-cli 可执行文件路径必须是绝对路径",
    "Proton Pass reference must be pass://SHARE_ID/ITEM_ID[/FIELD]": "Proton Pass 引用必须是 pass://SHARE_ID/ITEM_ID[/FIELD]",
    "Proton Pass vault selector is invalid": "Proton Pass 保险库选择器无效",
    "Range start must be less than end": "范围起点必须小于终点",
    "Registry cannot be deleted": "镜像仓库无法删除",
    "Repository URL must be a remote (https/ssh/git), not a local path": "仓库 URL 必须是远程地址（https/ssh/git），不能是本地路径",
    "Repository is not reachable or the password is incorrect": "仓库不可达或密码不正确",
    "System schedules cannot be paused": "系统计划任务无法暂停",
    "System schedules cannot be removed": "系统计划任务无法移除",
    "Two services cannot bind the same host port; change one.": "两个服务不能绑定同一主机端口，请更改其中一个。",
    "Type must be \"file\" or \"directory\"": "类型必须为 \"file\" 或 \"directory\"",
    "Type must be smtp or apprise": "类型必须为 smtp 或 apprise",
    "Webhook config requires at least one URL": "webhook 配置至少需要一个 URL",

    // ===================== 提示消息 (123) =====================
    "Sign in": "登录",
    "Sign in to your Dockhand account": "登录你的 Dockhand 账户",
    "Signing in...": "登录中...",
    "Local account": "本地账户",
    "LDAP directory": "LDAP 目录",
    "Single sign-on": "单点登录",
    "Continue with": "继续使用",
    "or continue with": "或继续使用",
    "License expired": "许可证已过期",
    "Open shell": "打开终端",
    "Open in new tab": "在新标签页打开",
    "Collapse all": "全部折叠",
    "Expand all": "全部展开",
    "Live updates connected": "实时更新已连接",
    "Live updates disconnected": "实时更新已断开",
    "Live updates active - grid will auto-refresh": "实时更新已启用 - 列表将自动刷新",
    "Connecting to live updates...": "正在连接实时更新...",
    "Additional mount options appended to the mount string": "追加到挂载字符串的额外挂载选项",
    "Search running containers...": "搜索运行中的容器...",
    "Search for pages and actions": "搜索页面和操作",
    "Hawser (standard)": "Hawser（标准）",
    "Hawser (edge)": "Hawser（边缘）",
    "Theme: system": "主题：系统",
    "Theme: dark": "主题：深色",
    "Theme: light": "主题：浅色",
    "Stack deployed from library template": "已从模板库部署栈",
    "Template reverted to default": "模板已恢复默认",
    "Permissions changed": "权限已更改",
    "Scanner cache was already empty": "扫描器缓存已是空的",
    "Select a repository": "请选择仓库",
    "Select a backup repository": "请选择备份仓库",
    "Please select a repository first": "请先选择仓库",
    "Please enter a repository URL first": "请先输入仓库 URL",
    "Unlock tiles": "解锁磁贴",
    "Check for updates": "检查更新",
    "Prune unused": "清理未使用",
    "Switch to vertical layout (logs on side)": "切换为垂直布局（日志在侧边）",
    "Export volume as tar": "导出卷为 tar",
    "Select a container from the list": "从列表中选择容器",
    "Notifications alt+T": "通知 alt+T",
    "Create compose stack": "创建 compose 栈",
    "Create a new Docker Compose stack": "创建新的 Docker Compose 栈",
    "Enter stack name above": "请在上方输入栈名称",
    "Create & Start": "创建并启动",
    "Browse for env file": "浏览环境变量文件",
    "Search a registry to find and pull images": "搜索镜像仓库以查找并拉取镜像",
    "Not deployed": "未部署",
    "Switch to horizontal layout (logs/terminal below)": "切换为水平布局（日志/终端在下方）",
    "Switch to horizontal layout (logs below)": "切换为水平布局（日志在下方）",
    "Select a container to view logs": "请选择容器以查看日志",
    "Out of memory": "内存不足",
    "Health status": "健康状态",
    "Last 7 days": "最近 7 天",
    "Last 30 days": "最近 30 天",
    "This month": "本月",
    "Last month": "上月",
    "Add a provider (1Password, Infisical, HashiCorp Vault, ...) to load secrets at deploy time": "添加提供方（1Password、Infisical、HashiCorp Vault 等），用于在部署时加载密钥",
    "Automatically removes temporary containers used for browsing volume contents. Runs every 30 minutes and on startup.": "自动删除用于浏览卷内容的临时容器。每 30 分钟及启动时运行。",
    "Configure notification channels to receive alerts about Docker events. Supports SMTP email and webhook URLs (Discord, Slack, Telegram, ntfy, Bark, Signal, Apprise, and more).": "配置通知渠道以接收 Docker 事件告警。支持 SMTP 邮件和 webhook URL（Discord、Slack、Telegram、ntfy、Bark、Signal、Apprise 等）。",
    "Add a channel to start receiving alerts about Docker events": "添加渠道以开始接收 Docker 事件告警",
    "Authentication is disabled - open access": "身份验证已禁用 - 开放访问",
    "Enable authentication to activate audit logging": "启用身份验证以激活审计日志",
    "Search for images...": "搜索镜像...",
    "These variables will be written to a .env file in the stack directory and passed to the compose command.": "这些变量将被写入栈目录中的 .env 文件，并传递给 compose 命令。",
    "Click source service": "点击源服务",
    "Click target service": "点击目标服务",
    "Net I/O": "网络 I/O",
    "Switch to vertical layout (logs/terminal on side)": "切换为垂直布局（日志/终端在侧边）",
    "Load from tar": "从 tar 加载",
    "All envs": "全部环境",
    "Hide system": "隐藏系统任务",
    "Last run": "上次运行",
    "Next run": "下次运行",
    "Removes container events older than 30 days": "删除 30 天前的容器事件",
    "Removes scanner vulnerability database cache to reclaim disk space": "清理扫描器漏洞数据库缓存以回收磁盘空间",
    "Removes execution logs older than 30 days": "删除 30 天前的执行日志",
    "Cleans up temporary volume browser containers": "清理临时的卷浏览容器",
    "System UI": "系统 UI",
    "System Monospace": "系统等宽字体",
    "Advanced settings": "高级设置",
    "Clear cache": "清除缓存",
    "as placeholder for the image name": "作为镜像名的占位符",
    "Docker not accessible": "Docker 不可访问",
    "Please enter a name for the new volume": "请输入新卷的名称",
    "Please enter the verification code": "请输入验证码",
    "Please select an image file": "请选择镜像文件",
    "Stream ended": "流已结束",
    "All sources are reachable": "所有源均可访问",
    "Applied — no restart needed": "已应用 — 无需重启",
    "Container paused": "容器已暂停",
    "Container restarted": "容器已重启",
    "Container started": "容器已启动",
    "Container stopped": "容器已停止",
    "Container unpaused": "容器已恢复",
    "MFA disabled for user": "已禁用该用户的 MFA",
    "No compose stacks found in this directory": "此目录中未找到 compose 栈",
    "No dangling images to prune": "没有可清理的悬空镜像",
    "No environment variables found": "未找到环境变量",
    "No unused images to prune": "没有可清理的未使用镜像",
    "A config set with this name already exists": "已存在同名配置集",
    "A credential with this name already exists": "已存在同名凭据",
    "A destination with this name already exists": "已存在同名目标",
    "A git stack with this name already exists for this environment": "此环境已存在同名 Git 栈",
    "A group with this name already exists": "已存在同名组",
    "A registry with this name already exists": "已存在同名镜像仓库",
    "A repository with this name already exists": "已存在同名仓库",
    "A secret provider with this name already exists": "已存在同名密钥提供方",
    "A stack with this name already exists on this environment": "此环境已存在同名栈",
    "An environment with this name already exists": "已存在同名环境",
    "Config set name already exists": "配置集名称已存在",
    "Destination already exists": "目标已存在",
    "Path already exists": "路径已存在",
    "Repository name already exists": "仓库名称已存在",
    "Role name already exists": "角色名称已存在",
    "Username already exists": "用户名已存在",
    "Content is too large (max 1MB)": "内容过大（最大 1MB）",
    "Current password is incorrect": "当前密码不正确",
    "Directory not empty": "目录不为空",
    "File is too large to edit (max 1MB)": "文件过大，无法编辑（最大 1MB）",
    "File is too large to view (max 1MB)": "文件过大，无法查看（最大 1MB）",
    "Image too large": "镜像过大",
    "Image too large. Maximum size is 500KB.": "镜像过大。最大为 500KB。",
    "Socket / system path - not backed up": "socket / 系统路径 - 不备份",
  };

  // ============ 插值模板：正则 -> 替换 ============
  const patterns = [
    [/^License expires in (\d+) days$/, "许可证将在 $1 天后到期"],
    [/^(\d+) of (\d+)$/, "$1 / $2"],
    [/^Cannot switch to "(.+?)" - (.+)$/, '无法切换到 "$1" - $2'],
    [/^(\d+) cores?$/, "$1 核"],
    [/^(.+?) RAM$/, "$1 内存"],
    [/^(\d+) unhealthy$/, "$1 个不健康"],
    [/^(\d+) restarting$/, "$1 个重启中"],
    [/^(\d+) today$/, "今日 $1"],
    [/^(\d+)m$/, "$1 分钟"],
    [/^(\d+)h$/, "$1 小时"],
    [/^(\d+)d$/, "$1 天"],
    [/^(\d+) total$/, "共 $1"],
    [/^(\d+) days$/, "$1 天"],
    [/^Failed to (.+)$/, "失败：$1"],
    // ---- 实测补充 v1.1.0 ----
    [/^\/ (\d+) total$/, "/ 共 $1"],
    [/^(\d+) seconds?$/, "$1 秒"],
    [/^(\d+) minutes?$/, "$1 分钟"],
    [/^(\d+) hours?$/, "$1 小时"],
    [/^(\d+) weeks?$/, "$1 周"],
    [/^(\d+) months?$/, "$1 个月"],
    [/^(\d+) years?$/, "$1 年"],
    [/^In (\d+) hours?$/, "$1 小时后"],
    [/^In (\d+) min(ute)?s?$/, "$1 分钟后"],
    [/^(\d+)d (\d+)h$/, "$1 天 $2 小时"],
    [/^Every (\d+) minutes$/, "每 $1 分钟"],
    [/^At ([\d:]+ [AP]M)$/, "于 $1"],
    [/^At ([\d:]+ [AP]M), only on Sunday$/, "每周日 $1"],
    // ---- v1.1.3 新增 ----
    [/^Checking (\d+)\/(\d+)$/, "检查中 $1/$2"],
    [/^(\d+) update\(s\) available \((\d+) failed to check\)$/, "$1 个可用更新（$2 个检查失败）"],
    [/^(.+): Could not query registry$/, "$1：无法查询镜像仓库"],
    [/^(\d+) volumes? mounted$/, "挂载了 $1 个卷"],
    [/^Version (.+)$/, "版本 $1"],
    [/^Update all \((\d+)\)$/, "全部更新 ($1)"],
    [/^(\d+) of (\d+) selected$/, "已选 $1/$2"],
    [/^Uptime (.+)$/, "运行时长 $1"]
  ];

  // ============ 翻译引擎 ============
  const ATTRS = ["placeholder", "title", "aria-label"];
  const SKIP_TAGS = new Set(["SCRIPT", "STYLE", "CODE", "PRE", "TEXTAREA", "NOSCRIPT", "KBD", "SAMP"]);
  const MAX_LEN = 300;

  // 翻译记录（用于还原）
  const textLog = new Map(); // textNode -> 原始完整文本
  const attrLog = new Map(); // element -> { attr: 原始值 }

  let enabled = localStorage.getItem("dh_zh_on") !== "0"; // 默认开启翻译

  function lookup(s) {
    if (dict[s]) return dict[s];
    const folded = s.replace(/\s+/g, " "); // 空白折叠：多行/制表符文本节点兜底
    if (dict[folded]) return dict[folded];
    if (s.length <= MAX_LEN) {
      for (const [re, rep] of patterns) {
        if (re.test(s)) return s.replace(re, rep);
      }
    }
    return null;
  }

  function translateTextNode(node) {
    const raw = node.nodeValue;
    if (!raw) return;
    const m = raw.match(/^(\s*)([\s\S]*?)(\s*)$/);
    if (!m || !m[2] || m[2].length > MAX_LEN) return;
    const zh = lookup(m[2]);
    if (!zh || zh === m[2]) return;
    textLog.set(node, raw); // 命中时当前必为英文，记录原始值
    node.nodeValue = m[1] + zh + m[3];
  }

  function translateElement(el) {
    for (const a of ATTRS) {
      const v = el.getAttribute(a);
      if (!v || v.length > MAX_LEN) continue;
      const zh = lookup(v);
      if (!zh || zh === v) continue;
      let log = attrLog.get(el);
      if (!log) { log = {}; attrLog.set(el, log); }
      if (!(a in log)) log[a] = v;
      el.setAttribute(a, zh);
    }
  }

  function isInEditor(el) {
    // 跳过代码编辑器（CodeMirror 6 / Monaco / contenteditable）内的文本
    return !!(el && el.closest && el.closest(
      '.cm-editor, .cm-content, .cm-line, [contenteditable="true"], [contenteditable=""], textarea, pre, code'
    ));
  }

  function walk(root) {
    if (root.nodeType === Node.TEXT_NODE) { if (!isInEditor(root.parentNode)) translateTextNode(root); return; }
    if (root.nodeType !== Node.ELEMENT_NODE) return;
    if (root.id === "dh-zh-toggle") return; // 不处理自身按钮
    translateElement(root); // 先翻译属性（含 textarea/input 的 placeholder），SKIP 元素也要翻属性
    if (SKIP_TAGS.has(root.tagName)) return; // 但跳过内容子树（脚本/样式/代码/textarea 内容不翻）
    if (isInEditor(root)) return; // 不进入代码编辑器子树
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT, {
      acceptNode(n) {
        if (n.nodeType === Node.TEXT_NODE) {
          return isInEditor(n.parentNode) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
        }
        if (n.id === "dh-zh-toggle") return NodeFilter.FILTER_REJECT;
        translateElement(n); // 翻译该元素属性（textarea/input placeholder 等）
        if (SKIP_TAGS.has(n.tagName) || isInEditor(n)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    for (let n = walker.nextNode(); n; n = walker.nextNode()) {
      if (n.nodeType === Node.TEXT_NODE) translateTextNode(n);
      else translateElement(n);
    }
  }

  function restoreAll() {
    for (const [node, orig] of textLog) {
      if (node.isConnected) node.nodeValue = orig;
    }
    textLog.clear();
    for (const [el, log] of attrLog) {
      if (el.isConnected) for (const a in log) el.setAttribute(a, log[a]);
    }
    attrLog.clear();
  }

  // ============ MutationObserver ============
  const mo = new MutationObserver((muts) => {
    if (btn && !btn.isConnected && document.body) document.body.appendChild(btn); // 维持按钮存在
    if (!enabled) return;
    for (const mu of muts) {
      if (mu.type === "characterData") { translateTextNode(mu.target); continue; }
      if (mu.type === "attributes") { translateElement(mu.target); continue; } // 动态设置的 title/placeholder 等
      for (const n of mu.addedNodes) walk(n);
    }
  });

  function start() {
    mo.observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATTRS });
    walk(document.documentElement);
  }

  // ============ 开关按钮 ============
  let btn = null;

  function makeButton() {
    btn = document.createElement("button");
    btn.id = "dh-zh-toggle";
    btn.style.cssText = [
      "position:fixed", "right:16px", "bottom:16px", "z-index:2147483647",
      "padding:7px 16px", "border:none", "border-radius:999px",
      "background:rgba(28,30,34,0.88)", "color:#fff",
      "font:500 12px/1.4 system-ui,sans-serif", "letter-spacing:0.5px",
      "cursor:pointer", "box-shadow:0 2px 10px rgba(0,0,0,0.3)",
      "transition:background 0.15s", "user-select:none"
    ].join(";");
    btn.addEventListener("mouseenter", () => { btn.style.background = "rgba(50,54,60,0.92)"; });
    btn.addEventListener("mouseleave", () => { btn.style.background = "rgba(28,30,34,0.88)"; });
    btn.addEventListener("click", toggle);
    updateLabel();
    document.body.appendChild(btn);
  }

  function updateLabel() {
    if (!btn) return;
    btn.textContent = enabled ? "还原翻译" : "开启翻译";
    btn.title = enabled ? "点击还原为英文" : "点击开启中文翻译";
  }

  function toggle() {
    enabled = !enabled;
    localStorage.setItem("dh_zh_on", enabled ? "1" : "0");
    if (enabled) {
      walk(document.documentElement); // 重新翻译当前 DOM
    } else {
      restoreAll(); // 还原所有已翻译文本
    }
    updateLabel();
  }

  // ============ 启动 ============
  if (document.body) {
    makeButton();
    if (enabled) start();
    else mo.observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATTRS }); // 仍监听以维持按钮存在
  } else {
    document.addEventListener("DOMContentLoaded", () => {
      makeButton();
      start();
    });
  }
})();
